-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity acquisition_serial_capture_inputs_to_mem is
port (
    rx_real_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    rx_real_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_real_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    rx_real_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    prn_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    prn_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    prn_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    prn_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    signal_buf_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    signal_buf_ce0 : OUT STD_LOGIC;
    signal_buf_d0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    signal_buf_q0 : IN STD_LOGIC_VECTOR (1 downto 0);
    signal_buf_we0 : OUT STD_LOGIC;
    signal_buf_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    signal_buf_ce1 : OUT STD_LOGIC;
    signal_buf_d1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    signal_buf_q1 : IN STD_LOGIC_VECTOR (1 downto 0);
    signal_buf_we1 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce1 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we1 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce1 : OUT STD_LOGIC;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_q1 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    rx_real_TVALID : IN STD_LOGIC;
    rx_real_TREADY : OUT STD_LOGIC;
    prn_in_TVALID : IN STD_LOGIC;
    prn_in_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of acquisition_serial_capture_inputs_to_mem is 
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';

attribute shreg_extract : string;
    signal read_inputs_to_stream_U0_ap_start : STD_LOGIC;
    signal read_inputs_to_stream_U0_ap_done : STD_LOGIC;
    signal read_inputs_to_stream_U0_ap_continue : STD_LOGIC;
    signal read_inputs_to_stream_U0_ap_idle : STD_LOGIC;
    signal read_inputs_to_stream_U0_ap_ready : STD_LOGIC;
    signal read_inputs_to_stream_U0_sig_s_din : STD_LOGIC_VECTOR (1 downto 0);
    signal read_inputs_to_stream_U0_sig_s_write : STD_LOGIC;
    signal read_inputs_to_stream_U0_prn_s_din : STD_LOGIC_VECTOR (0 downto 0);
    signal read_inputs_to_stream_U0_prn_s_write : STD_LOGIC;
    signal read_inputs_to_stream_U0_start_out : STD_LOGIC;
    signal read_inputs_to_stream_U0_start_write : STD_LOGIC;
    signal read_inputs_to_stream_U0_rx_real_TREADY : STD_LOGIC;
    signal read_inputs_to_stream_U0_prn_in_TREADY : STD_LOGIC;
    signal store_stream_to_mem_U0_ap_start : STD_LOGIC;
    signal store_stream_to_mem_U0_ap_done : STD_LOGIC;
    signal store_stream_to_mem_U0_ap_continue : STD_LOGIC;
    signal store_stream_to_mem_U0_ap_idle : STD_LOGIC;
    signal store_stream_to_mem_U0_ap_ready : STD_LOGIC;
    signal store_stream_to_mem_U0_sig_s_read : STD_LOGIC;
    signal store_stream_to_mem_U0_prn_s_read : STD_LOGIC;
    signal store_stream_to_mem_U0_signal_buf_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal store_stream_to_mem_U0_signal_buf_ce0 : STD_LOGIC;
    signal store_stream_to_mem_U0_signal_buf_we0 : STD_LOGIC;
    signal store_stream_to_mem_U0_signal_buf_d0 : STD_LOGIC_VECTOR (1 downto 0);
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0 : STD_LOGIC;
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0 : STD_LOGIC;
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0 : STD_LOGIC;
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0 : STD_LOGIC;
    signal store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sig_s_full_n : STD_LOGIC;
    signal sig_s_dout : STD_LOGIC_VECTOR (1 downto 0);
    signal sig_s_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal sig_s_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal sig_s_empty_n : STD_LOGIC;
    signal prn_s_full_n : STD_LOGIC;
    signal prn_s_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal prn_s_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal prn_s_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal prn_s_empty_n : STD_LOGIC;
    signal start_for_store_stream_to_mem_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_stream_to_mem_U0_full_n : STD_LOGIC;
    signal start_for_store_stream_to_mem_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_store_stream_to_mem_U0_empty_n : STD_LOGIC;

    component acquisition_serial_read_inputs_to_stream IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rx_real_TVALID : IN STD_LOGIC;
        prn_in_TVALID : IN STD_LOGIC;
        sig_s_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        sig_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        sig_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        sig_s_full_n : IN STD_LOGIC;
        sig_s_write : OUT STD_LOGIC;
        prn_s_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        prn_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        prn_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        prn_s_full_n : IN STD_LOGIC;
        prn_s_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        rx_real_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_real_TREADY : OUT STD_LOGIC;
        rx_real_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        rx_real_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        rx_real_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        prn_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        prn_in_TREADY : OUT STD_LOGIC;
        prn_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        prn_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        prn_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component acquisition_serial_store_stream_to_mem IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sig_s_dout : IN STD_LOGIC_VECTOR (1 downto 0);
        sig_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        sig_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        sig_s_empty_n : IN STD_LOGIC;
        sig_s_read : OUT STD_LOGIC;
        prn_s_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        prn_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        prn_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        prn_s_empty_n : IN STD_LOGIC;
        prn_s_read : OUT STD_LOGIC;
        signal_buf_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        signal_buf_ce0 : OUT STD_LOGIC;
        signal_buf_we0 : OUT STD_LOGIC;
        signal_buf_d0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0 : OUT STD_LOGIC;
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0 : OUT STD_LOGIC;
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0 : OUT STD_LOGIC;
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0 : OUT STD_LOGIC;
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component acquisition_serial_fifo_w2_d64_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (1 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (1 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component acquisition_serial_fifo_w1_d64_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component acquisition_serial_start_for_store_stream_to_mem_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    read_inputs_to_stream_U0 : component acquisition_serial_read_inputs_to_stream
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => read_inputs_to_stream_U0_ap_start,
        start_full_n => start_for_store_stream_to_mem_U0_full_n,
        ap_done => read_inputs_to_stream_U0_ap_done,
        ap_continue => read_inputs_to_stream_U0_ap_continue,
        ap_idle => read_inputs_to_stream_U0_ap_idle,
        ap_ready => read_inputs_to_stream_U0_ap_ready,
        rx_real_TVALID => rx_real_TVALID,
        prn_in_TVALID => prn_in_TVALID,
        sig_s_din => read_inputs_to_stream_U0_sig_s_din,
        sig_s_num_data_valid => sig_s_num_data_valid,
        sig_s_fifo_cap => sig_s_fifo_cap,
        sig_s_full_n => sig_s_full_n,
        sig_s_write => read_inputs_to_stream_U0_sig_s_write,
        prn_s_din => read_inputs_to_stream_U0_prn_s_din,
        prn_s_num_data_valid => prn_s_num_data_valid,
        prn_s_fifo_cap => prn_s_fifo_cap,
        prn_s_full_n => prn_s_full_n,
        prn_s_write => read_inputs_to_stream_U0_prn_s_write,
        start_out => read_inputs_to_stream_U0_start_out,
        start_write => read_inputs_to_stream_U0_start_write,
        rx_real_TDATA => rx_real_TDATA,
        rx_real_TREADY => read_inputs_to_stream_U0_rx_real_TREADY,
        rx_real_TKEEP => rx_real_TKEEP,
        rx_real_TSTRB => rx_real_TSTRB,
        rx_real_TLAST => rx_real_TLAST,
        prn_in_TDATA => prn_in_TDATA,
        prn_in_TREADY => read_inputs_to_stream_U0_prn_in_TREADY,
        prn_in_TKEEP => prn_in_TKEEP,
        prn_in_TSTRB => prn_in_TSTRB,
        prn_in_TLAST => prn_in_TLAST);

    store_stream_to_mem_U0 : component acquisition_serial_store_stream_to_mem
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => store_stream_to_mem_U0_ap_start,
        ap_done => store_stream_to_mem_U0_ap_done,
        ap_continue => store_stream_to_mem_U0_ap_continue,
        ap_idle => store_stream_to_mem_U0_ap_idle,
        ap_ready => store_stream_to_mem_U0_ap_ready,
        sig_s_dout => sig_s_dout,
        sig_s_num_data_valid => sig_s_num_data_valid,
        sig_s_fifo_cap => sig_s_fifo_cap,
        sig_s_empty_n => sig_s_empty_n,
        sig_s_read => store_stream_to_mem_U0_sig_s_read,
        prn_s_dout => prn_s_dout,
        prn_s_num_data_valid => prn_s_num_data_valid,
        prn_s_fifo_cap => prn_s_fifo_cap,
        prn_s_empty_n => prn_s_empty_n,
        prn_s_read => store_stream_to_mem_U0_prn_s_read,
        signal_buf_address0 => store_stream_to_mem_U0_signal_buf_address0,
        signal_buf_ce0 => store_stream_to_mem_U0_signal_buf_ce0,
        signal_buf_we0 => store_stream_to_mem_U0_signal_buf_we0,
        signal_buf_d0 => store_stream_to_mem_U0_signal_buf_d0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0,
        acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0 => store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0);

    sig_s_U : component acquisition_serial_fifo_w2_d64_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_inputs_to_stream_U0_sig_s_din,
        if_full_n => sig_s_full_n,
        if_write => read_inputs_to_stream_U0_sig_s_write,
        if_dout => sig_s_dout,
        if_num_data_valid => sig_s_num_data_valid,
        if_fifo_cap => sig_s_fifo_cap,
        if_empty_n => sig_s_empty_n,
        if_read => store_stream_to_mem_U0_sig_s_read);

    prn_s_U : component acquisition_serial_fifo_w1_d64_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_inputs_to_stream_U0_prn_s_din,
        if_full_n => prn_s_full_n,
        if_write => read_inputs_to_stream_U0_prn_s_write,
        if_dout => prn_s_dout,
        if_num_data_valid => prn_s_num_data_valid,
        if_fifo_cap => prn_s_fifo_cap,
        if_empty_n => prn_s_empty_n,
        if_read => store_stream_to_mem_U0_prn_s_read);

    start_for_store_stream_to_mem_U0_U : component acquisition_serial_start_for_store_stream_to_mem_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_store_stream_to_mem_U0_din,
        if_full_n => start_for_store_stream_to_mem_U0_full_n,
        if_write => read_inputs_to_stream_U0_start_write,
        if_dout => start_for_store_stream_to_mem_U0_dout,
        if_empty_n => start_for_store_stream_to_mem_U0_empty_n,
        if_read => store_stream_to_mem_U0_ap_ready);




    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_address1 <= ap_const_lv14_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_ce1 <= ap_const_logic_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_d1 <= ap_const_lv1_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_4_we1 <= ap_const_logic_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_address1 <= ap_const_lv14_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_ce1 <= ap_const_logic_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_d1 <= ap_const_lv1_0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0 <= store_stream_to_mem_U0_acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we0;
    acquisition_serial_stream_stream_stream_int_int_int_int_int_int_int_int_5_we1 <= ap_const_logic_0;
    ap_done <= store_stream_to_mem_U0_ap_done;
    ap_idle <= (store_stream_to_mem_U0_ap_idle and read_inputs_to_stream_U0_ap_idle);
    ap_ready <= read_inputs_to_stream_U0_ap_ready;
    prn_in_TREADY <= read_inputs_to_stream_U0_prn_in_TREADY;
    read_inputs_to_stream_U0_ap_continue <= ap_const_logic_1;
    read_inputs_to_stream_U0_ap_start <= ap_start;
    rx_real_TREADY <= read_inputs_to_stream_U0_rx_real_TREADY;
    signal_buf_address0 <= store_stream_to_mem_U0_signal_buf_address0;
    signal_buf_address1 <= ap_const_lv14_0;
    signal_buf_ce0 <= store_stream_to_mem_U0_signal_buf_ce0;
    signal_buf_ce1 <= ap_const_logic_0;
    signal_buf_d0 <= store_stream_to_mem_U0_signal_buf_d0;
    signal_buf_d1 <= ap_const_lv2_0;
    signal_buf_we0 <= store_stream_to_mem_U0_signal_buf_we0;
    signal_buf_we1 <= ap_const_logic_0;
    start_for_store_stream_to_mem_U0_din <= (0=>ap_const_logic_1, others=>'-');
    store_stream_to_mem_U0_ap_continue <= ap_continue;
    store_stream_to_mem_U0_ap_start <= start_for_store_stream_to_mem_U0_empty_n;
end behav;
