
wire kernel_monitor_reset;
wire kernel_monitor_clock;
wire kernel_monitor_report;
assign kernel_monitor_reset = ~ap_rst_n;
assign kernel_monitor_clock = ap_clk;
assign kernel_monitor_report = 1'b0;
wire [2:0] axis_block_sigs;
wire [15:0] inst_idle_sigs;
wire [6:0] inst_block_sigs;
wire kernel_block;

assign axis_block_sigs[0] = ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.rx_stream_TDATA_blk_n;
assign axis_block_sigs[1] = ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.prn_stream_TDATA_blk_n;
assign axis_block_sigs[2] = ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.grp_write_corr_out_stream_Pipeline_WRITE_CORR_fu_60.corr_out_TDATA_blk_n;

assign inst_idle_sigs[0] = grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.ap_idle;
assign inst_block_sigs[0] = (grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.produce_fine_powers_U0.grp_process_all_variants_all_tau_fu_245.grp_process_all_variants_all_tau_Pipeline_STORE_VARIANT_ALL_fu_2177.pow_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.produce_fine_powers_U0.fine_tau_count_c13_blk_n;
assign inst_idle_sigs[1] = grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.store_stream_to_mem_stsa_U0.ap_idle;
assign inst_block_sigs[1] = (grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.store_stream_to_mem_stsa_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.store_stream_to_mem_stsa_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.grp_reduce_fine_stream_core_Pipeline_REDUCE_TAU_fu_184.pow_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.max_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.grp_reduce_fine_stream_core_Pipeline_REDUCE_TAU_fu_184.corr_pkt_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.fine_tau_count_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.stats_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.fine_tau_count_c_blk_n;
assign inst_idle_sigs[2] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.produce_fine_powers_U0.ap_idle;
assign inst_block_sigs[2] = (grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.produce_fine_powers_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.produce_fine_powers_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.grp_write_corr_out_stream_Pipeline_WRITE_CORR_fu_60.corr_pkt_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.fine_tau_count_blk_n;
assign inst_idle_sigs[3] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.ap_idle;
assign inst_block_sigs[3] = (grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.reduce_fine_stream_core_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.consume_fine_maxima_and_insert_U0.max_s_blk_n;
assign inst_idle_sigs[4] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.ap_idle;
assign inst_block_sigs[4] = (grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.read_fine_stats_U0.stats_s_blk_n;
assign inst_idle_sigs[5] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.consume_fine_maxima_and_insert_U0.ap_idle;
assign inst_block_sigs[5] = (grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.consume_fine_maxima_and_insert_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.consume_fine_maxima_and_insert_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.sig_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.prn_s_blk_n;
assign inst_idle_sigs[6] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.read_fine_stats_U0.ap_idle;
assign inst_block_sigs[6] = (grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.read_fine_stats_U0.ap_done & ~grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.read_fine_stats_U0.ap_continue) | ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.store_stream_to_mem_stsa_U0.sig_s_blk_n | ~grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.store_stream_to_mem_stsa_U0.prn_s_blk_n;

assign inst_idle_sigs[7] = 1'b0;
assign inst_idle_sigs[8] = grp_acquisition_stsa_fu_229.ap_idle;
assign inst_idle_sigs[9] = grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.ap_idle;
assign inst_idle_sigs[10] = grp_acquisition_stsa_fu_229.grp_capture_inputs_to_mem_stsa_fu_262.read_inputs_to_stream_stsa_U0.ap_idle;
assign inst_idle_sigs[11] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.ap_idle;
assign inst_idle_sigs[12] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.ap_idle;
assign inst_idle_sigs[13] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.ap_idle;
assign inst_idle_sigs[14] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.ap_idle;
assign inst_idle_sigs[15] = grp_acquisition_stsa_fu_229.grp_fine_search_fu_454.grp_run_fine_dataflow_region_fu_1201.grp_run_fine_dataflow_core_fu_166.write_corr_out_stream_U0.grp_write_corr_out_stream_Pipeline_WRITE_CORR_fu_60.ap_idle;

acquisition_stsa_top_hls_deadlock_idx0_monitor acquisition_stsa_top_hls_deadlock_idx0_monitor_U (
    .clock(kernel_monitor_clock),
    .reset(kernel_monitor_reset),
    .axis_block_sigs(axis_block_sigs),
    .inst_idle_sigs(inst_idle_sigs),
    .inst_block_sigs(inst_block_sigs),
    .block(kernel_block)
);


always @ (kernel_block or kernel_monitor_reset) begin
    if (kernel_block == 1'b1 && kernel_monitor_reset == 1'b0) begin
        find_kernel_block = 1'b1;
    end
    else begin
        find_kernel_block = 1'b0;
    end
end
