// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module acquisition_stsa_top_fine_mix_to_mem (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        signal_r_address0,
        signal_r_ce0,
        signal_r_q0,
        mix_i_0_address0,
        mix_i_0_ce0,
        mix_i_0_we0,
        mix_i_0_d0,
        mix_i_1_address0,
        mix_i_1_ce0,
        mix_i_1_we0,
        mix_i_1_d0,
        mix_q_0_address0,
        mix_q_0_ce0,
        mix_q_0_we0,
        mix_q_0_d0,
        mix_q_1_address0,
        mix_q_1_ce0,
        mix_q_1_we0,
        mix_q_1_d0,
        fd_val
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] signal_r_address0;
output   signal_r_ce0;
input  [15:0] signal_r_q0;
output  [12:0] mix_i_0_address0;
output   mix_i_0_ce0;
output   mix_i_0_we0;
output  [15:0] mix_i_0_d0;
output  [12:0] mix_i_1_address0;
output   mix_i_1_ce0;
output   mix_i_1_we0;
output  [15:0] mix_i_1_d0;
output  [12:0] mix_q_0_address0;
output   mix_q_0_ce0;
output   mix_q_0_we0;
output  [15:0] mix_q_0_d0;
output  [12:0] mix_q_1_address0;
output   mix_q_1_ce0;
output   mix_q_1_we0;
output  [15:0] mix_q_1_d0;
input  [23:0] fd_val;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [24:0] sub_ln4851_fu_82_p2;
reg   [24:0] sub_ln4851_reg_151;
reg   [0:0] tmp_reg_156;
wire    ap_CS_fsm_state2;
wire   [115:0] grp_fu_73_p2;
reg   [115:0] mul_ln4851_reg_167;
wire    ap_CS_fsm_state6;
reg   [31:0] tmp_29_cast_reg_172;
wire   [115:0] sub_ln4851_1_fu_118_p2;
reg   [115:0] sub_ln4851_1_reg_178;
wire    ap_CS_fsm_state7;
wire   [31:0] phase_inc_fu_144_p3;
reg   [31:0] phase_inc_reg_183;
wire    ap_CS_fsm_state8;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_done;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_idle;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_ready;
wire   [12:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_address0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_ce0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_we0;
wire   [15:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_d0;
wire   [12:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_address0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_ce0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_we0;
wire   [15:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_d0;
wire   [12:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_address0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_ce0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_we0;
wire   [15:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_d0;
wire   [12:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_address0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_ce0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_we0;
wire   [15:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_d0;
wire   [13:0] grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_signal_r_address0;
wire    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_signal_r_ce0;
reg    grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start_reg;
wire    ap_CS_fsm_state9;
wire   [59:0] grp_fu_73_p1;
wire  signed [24:0] sext_ln4851_fu_78_p1;
wire  signed [56:0] tmp_s_fu_96_p3;
wire   [31:0] tmp_28_cast_fu_123_p4;
wire   [31:0] select_ln4851_fu_132_p3;
wire   [31:0] sub_ln4851_2_fu_138_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start_reg = 1'b0;
end

acquisition_stsa_top_fine_mix_to_mem_Pipeline_MIX_LOOP grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start),
    .ap_done(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_done),
    .ap_idle(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_idle),
    .ap_ready(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_ready),
    .phase_inc(phase_inc_reg_183),
    .mix_i_1_address0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_address0),
    .mix_i_1_ce0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_ce0),
    .mix_i_1_we0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_we0),
    .mix_i_1_d0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_d0),
    .mix_i_0_address0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_address0),
    .mix_i_0_ce0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_ce0),
    .mix_i_0_we0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_we0),
    .mix_i_0_d0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_d0),
    .mix_q_1_address0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_address0),
    .mix_q_1_ce0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_ce0),
    .mix_q_1_we0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_we0),
    .mix_q_1_d0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_d0),
    .mix_q_0_address0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_address0),
    .mix_q_0_ce0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_ce0),
    .mix_q_0_we0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_we0),
    .mix_q_0_d0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_d0),
    .signal_r_address0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_signal_r_address0),
    .signal_r_ce0(grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_signal_r_ce0),
    .signal_r_q0(signal_r_q0)
);

acquisition_stsa_top_mul_57s_60ns_116_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 57 ),
    .din1_WIDTH( 60 ),
    .dout_WIDTH( 116 ))
mul_57s_60ns_116_5_1_U759(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_fu_96_p3),
    .din1(grp_fu_73_p1),
    .ce(1'b1),
    .dout(grp_fu_73_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_ready == 1'b1)) begin
            grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln4851_reg_167 <= grp_fu_73_p2;
        tmp_29_cast_reg_172 <= {{grp_fu_73_p2[113:82]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        phase_inc_reg_183 <= phase_inc_fu_144_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        sub_ln4851_1_reg_178 <= sub_ln4851_1_fu_118_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub_ln4851_reg_151 <= sub_ln4851_fu_82_p2;
        tmp_reg_156 <= sub_ln4851_fu_82_p2[32'd24];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_ap_start_reg;

assign grp_fu_73_p1 = 116'd403008857276316085;

assign mix_i_0_address0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_address0;

assign mix_i_0_ce0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_ce0;

assign mix_i_0_d0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_d0;

assign mix_i_0_we0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_0_we0;

assign mix_i_1_address0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_address0;

assign mix_i_1_ce0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_ce0;

assign mix_i_1_d0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_d0;

assign mix_i_1_we0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_i_1_we0;

assign mix_q_0_address0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_address0;

assign mix_q_0_ce0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_ce0;

assign mix_q_0_d0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_d0;

assign mix_q_0_we0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_0_we0;

assign mix_q_1_address0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_address0;

assign mix_q_1_ce0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_ce0;

assign mix_q_1_d0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_d0;

assign mix_q_1_we0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_mix_q_1_we0;

assign phase_inc_fu_144_p3 = ((tmp_reg_156[0:0] == 1'b1) ? sub_ln4851_2_fu_138_p2 : tmp_29_cast_reg_172);

assign select_ln4851_fu_132_p3 = ((tmp_reg_156[0:0] == 1'b1) ? tmp_28_cast_fu_123_p4 : tmp_29_cast_reg_172);

assign sext_ln4851_fu_78_p1 = $signed(fd_val);

assign signal_r_address0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_signal_r_address0;

assign signal_r_ce0 = grp_fine_mix_to_mem_Pipeline_MIX_LOOP_fu_54_signal_r_ce0;

assign sub_ln4851_1_fu_118_p2 = (116'd0 - mul_ln4851_reg_167);

assign sub_ln4851_2_fu_138_p2 = (32'd0 - select_ln4851_fu_132_p3);

assign sub_ln4851_fu_82_p2 = ($signed(25'd29991432) - $signed(sext_ln4851_fu_78_p1));

assign tmp_28_cast_fu_123_p4 = {{sub_ln4851_1_reg_178[113:82]}};

assign tmp_s_fu_96_p3 = {{sub_ln4851_reg_151}, {32'd0}};

endmodule //acquisition_stsa_top_fine_mix_to_mem
