// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module acquisition_stsa_top_build_prn_variants_Pipeline_BUILD_PRN_BASE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        prn_address0,
        prn_ce0,
        prn_q0,
        prn_address1,
        prn_ce1,
        prn_q1,
        prn_address2,
        prn_ce2,
        prn_q2,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_address0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_ce0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_we0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_d0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_address0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_ce0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_we0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_d0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_address0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_ce0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_we0,
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] prn_address0;
output   prn_ce0;
input  [15:0] prn_q0;
output  [13:0] prn_address1;
output   prn_ce1;
input  [15:0] prn_q1;
output  [13:0] prn_address2;
output   prn_ce2;
input  [15:0] prn_q2;
output  [14:0] acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_address0;
output   acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_ce0;
output   acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_we0;
output  [0:0] acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_d0;
output  [14:0] acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_address0;
output   acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_ce0;
output   acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_we0;
output  [0:0] acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_d0;
output  [14:0] acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_address0;
output   acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_ce0;
output   acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_we0;
output  [0:0] acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_d0;

reg ap_idle;
reg prn_ce0;
reg prn_ce1;
reg prn_ce2;
reg acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_ce0;
reg acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_we0;
reg acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_ce0;
reg acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_we0;
reg acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_ce0;
reg acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln5427_fu_136_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [13:0] add_ln5429_fu_142_p2;
reg   [13:0] add_ln5429_reg_289;
wire   [63:0] zext_ln5427_fu_148_p1;
reg   [63:0] zext_ln5427_reg_295;
reg   [63:0] zext_ln5427_reg_295_pp0_iter1_reg;
reg   [63:0] zext_ln5427_reg_295_pp0_iter2_reg;
wire   [13:0] prev_idx_fu_179_p3;
reg   [13:0] prev_idx_reg_302;
reg  signed [15:0] x_reg_312;
reg   [0:0] tmp_reg_327;
reg   [0:0] tmp_51_reg_332;
reg   [0:0] tmp_52_reg_337;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln5433_fu_204_p1;
wire   [63:0] zext_ln5434_fu_209_p1;
reg   [13:0] i_fu_48;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_i_10;
wire   [14:0] zext_ln5430_fu_153_p1;
wire   [14:0] add_ln5430_fu_157_p2;
wire   [0:0] empty_168_fu_167_p2;
wire   [13:0] empty_167_fu_163_p1;
wire   [13:0] empty_169_fu_173_p2;
wire   [0:0] empty_fu_192_p2;
wire   [13:0] next_idx_fu_197_p3;
wire  signed [15:0] tmp_fu_213_p1;
wire  signed [16:0] sext_ln5433_1_fu_224_p1;
wire  signed [16:0] sext_ln5433_fu_221_p1;
wire  signed [16:0] sext_ln5434_fu_234_p1;
wire   [16:0] add_ln5433_fu_228_p2;
wire   [16:0] add_ln5434_fu_238_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 i_fu_48 = 14'd0;
#0 ap_done_reg = 1'b0;
end

acquisition_stsa_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln5427_fu_136_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_48 <= add_ln5429_fu_142_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln5429_reg_289 <= add_ln5429_fu_142_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        prev_idx_reg_302 <= prev_idx_fu_179_p3;
        tmp_reg_327 <= tmp_fu_213_p1[32'd15];
        zext_ln5427_reg_295[13 : 0] <= zext_ln5427_fu_148_p1[13 : 0];
        zext_ln5427_reg_295_pp0_iter1_reg[13 : 0] <= zext_ln5427_reg_295[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_51_reg_332 <= add_ln5433_fu_228_p2[32'd16];
        tmp_52_reg_337 <= add_ln5434_fu_238_p2[32'd16];
        zext_ln5427_reg_295_pp0_iter2_reg[13 : 0] <= zext_ln5427_reg_295_pp0_iter1_reg[13 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_reg_312 <= prn_q2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_ce0 = 1'b1;
    end else begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_we0 = 1'b1;
    end else begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_ce0 = 1'b1;
    end else begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_we0 = 1'b1;
    end else begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_ce0 = 1'b1;
    end else begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_we0 = 1'b1;
    end else begin
        acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5427_fu_136_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_10 = 14'd0;
    end else begin
        ap_sig_allocacmp_i_10 = i_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prn_ce0 = 1'b1;
    end else begin
        prn_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prn_ce1 = 1'b1;
    end else begin
        prn_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prn_ce2 = 1'b1;
    end else begin
        prn_ce2 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_address0 = zext_ln5427_reg_295_pp0_iter2_reg;

assign acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_1_d0 = (tmp_51_reg_332 ^ 1'd1);

assign acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_address0 = zext_ln5427_reg_295_pp0_iter1_reg;

assign acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_2_d0 = (tmp_reg_327 ^ 1'd1);

assign acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_address0 = zext_ln5427_reg_295_pp0_iter2_reg;

assign acquisition_stsa_stream_stream_stream_int_int_ap_ufixed_bool_ap_ufixed_ap_d0 = (tmp_52_reg_337 ^ 1'd1);

assign add_ln5429_fu_142_p2 = (ap_sig_allocacmp_i_10 + 14'd1);

assign add_ln5430_fu_157_p2 = (zext_ln5430_fu_153_p1 + 15'd11998);

assign add_ln5433_fu_228_p2 = ($signed(sext_ln5433_1_fu_224_p1) + $signed(sext_ln5433_fu_221_p1));

assign add_ln5434_fu_238_p2 = ($signed(sext_ln5434_fu_234_p1) + $signed(sext_ln5433_fu_221_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_167_fu_163_p1 = add_ln5430_fu_157_p2[13:0];

assign empty_168_fu_167_p2 = ((add_ln5430_fu_157_p2 < 15'd11999) ? 1'b1 : 1'b0);

assign empty_169_fu_173_p2 = ($signed(ap_sig_allocacmp_i_10) + $signed(14'd16383));

assign empty_fu_192_p2 = ((add_ln5429_reg_289 == 14'd11999) ? 1'b1 : 1'b0);

assign icmp_ln5427_fu_136_p2 = ((ap_sig_allocacmp_i_10 == 14'd11999) ? 1'b1 : 1'b0);

assign next_idx_fu_197_p3 = ((empty_fu_192_p2[0:0] == 1'b1) ? 14'd0 : add_ln5429_reg_289);

assign prev_idx_fu_179_p3 = ((empty_168_fu_167_p2[0:0] == 1'b1) ? empty_167_fu_163_p1 : empty_169_fu_173_p2);

assign prn_address0 = zext_ln5434_fu_209_p1;

assign prn_address1 = zext_ln5433_fu_204_p1;

assign prn_address2 = zext_ln5427_fu_148_p1;

assign sext_ln5433_1_fu_224_p1 = $signed(prn_q1);

assign sext_ln5433_fu_221_p1 = x_reg_312;

assign sext_ln5434_fu_234_p1 = $signed(prn_q0);

assign tmp_fu_213_p1 = prn_q2;

assign zext_ln5427_fu_148_p1 = ap_sig_allocacmp_i_10;

assign zext_ln5430_fu_153_p1 = ap_sig_allocacmp_i_10;

assign zext_ln5433_fu_204_p1 = next_idx_fu_197_p3;

assign zext_ln5434_fu_209_p1 = prev_idx_reg_302;

always @ (posedge ap_clk) begin
    zext_ln5427_reg_295[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln5427_reg_295_pp0_iter1_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
    zext_ln5427_reg_295_pp0_iter2_reg[63:14] <= 50'b00000000000000000000000000000000000000000000000000;
end

endmodule //acquisition_stsa_top_build_prn_variants_Pipeline_BUILD_PRN_BASE
