// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module acquisition_serial_reduce_all_powers_Pipeline_REDUCE_ALL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pow_s_dout,
        pow_s_num_data_valid,
        pow_s_fifo_cap,
        pow_s_empty_n,
        pow_s_read,
        corr_out_TREADY,
        max_val_in_load_cast,
        sum_corr_in_load_cast,
        total,
        sub,
        corr_out_TDATA,
        corr_out_TVALID,
        corr_out_TKEEP,
        corr_out_TSTRB,
        corr_out_TLAST,
        best_tau,
        best_tau_ap_vld,
        best_fd_idx,
        best_fd_idx_ap_vld,
        max_val_ininout_tmp_0_out,
        max_val_ininout_tmp_0_out_ap_vld,
        p_out,
        p_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] pow_s_dout;
input  [6:0] pow_s_num_data_valid;
input  [6:0] pow_s_fifo_cap;
input   pow_s_empty_n;
output   pow_s_read;
input   corr_out_TREADY;
input  [0:0] max_val_in_load_cast;
input  [0:0] sum_corr_in_load_cast;
input  [24:0] total;
input  [24:0] sub;
output  [31:0] corr_out_TDATA;
output   corr_out_TVALID;
output  [3:0] corr_out_TKEEP;
output  [3:0] corr_out_TSTRB;
output  [0:0] corr_out_TLAST;
output  [31:0] best_tau;
output   best_tau_ap_vld;
output  [31:0] best_fd_idx;
output   best_fd_idx_ap_vld;
output  [63:0] max_val_ininout_tmp_0_out;
output   max_val_ininout_tmp_0_out_ap_vld;
output  [63:0] p_out;
output   p_out_ap_vld;

reg ap_idle;
reg pow_s_read;
reg corr_out_TVALID;
reg best_tau_ap_vld;
reg best_fd_idx_ap_vld;
reg max_val_ininout_tmp_0_out_ap_vld;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln415_fu_210_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    corr_out_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    pow_s_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln415_reg_363;
wire   [0:0] out_last_fu_222_p2;
reg   [0:0] out_last_reg_367;
reg   [0:0] out_last_reg_367_pp0_iter1_reg;
wire   [63:0] p_power_fu_233_p1;
reg   [63:0] p_power_reg_372;
reg   [31:0] p_tau_reg_379;
reg   [31:0] p_fd_idx_reg_384;
wire   [31:0] out_data_fu_299_p3;
reg   [31:0] out_data_reg_389;
reg   [24:0] i_fu_96;
wire   [24:0] i_3_fu_216_p2;
wire    ap_loop_init;
reg   [24:0] ap_sig_allocacmp_i_2;
reg   [63:0] empty_fu_100;
wire   [63:0] add_ln419_fu_313_p2;
wire   [63:0] sum_corr_in_load_cast_cast_fu_184_p1;
reg   [63:0] max_val_ininout_tmp_0_fu_104;
wire   [63:0] max_val_in_load_cast_cast_fu_188_p1;
wire   [0:0] icmp_ln422_fu_318_p2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] trunc_ln430_fu_275_p1;
wire   [31:0] tmp_fu_257_p4;
wire   [0:0] icmp_ln430_fu_279_p2;
wire   [31:0] add_ln430_fu_285_p2;
wire   [0:0] tmp_1_fu_267_p3;
wire   [31:0] select_ln430_fu_291_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_96 = 25'd0;
#0 empty_fu_100 = 64'd0;
#0 max_val_ininout_tmp_0_fu_104 = 64'd0;
#0 ap_done_reg = 1'b0;
end

acquisition_serial_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_fu_100 <= sum_corr_in_load_cast_cast_fu_184_p1;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            empty_fu_100 <= add_ln419_fu_313_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln415_fu_210_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_96 <= i_3_fu_216_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_96 <= 25'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_val_ininout_tmp_0_fu_104 <= max_val_in_load_cast_cast_fu_188_p1;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln422_fu_318_p2 == 1'd1))) begin
            max_val_ininout_tmp_0_fu_104 <= p_power_reg_372;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln415_reg_363 <= icmp_ln415_fu_210_p2;
        out_data_reg_389 <= out_data_fu_299_p3;
        out_last_reg_367 <= out_last_fu_222_p2;
        out_last_reg_367_pp0_iter1_reg <= out_last_reg_367;
        p_fd_idx_reg_384 <= {{pow_s_dout[127:96]}};
        p_power_reg_372 <= p_power_fu_233_p1;
        p_tau_reg_379 <= {{pow_s_dout[95:64]}};
    end
end

always @ (*) begin
    if (((icmp_ln415_fu_210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 25'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln422_fu_318_p2 == 1'd1))) begin
        best_fd_idx_ap_vld = 1'b1;
    end else begin
        best_fd_idx_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln422_fu_318_p2 == 1'd1))) begin
        best_tau_ap_vld = 1'b1;
    end else begin
        best_tau_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        corr_out_TDATA_blk_n = corr_out_TREADY;
    end else begin
        corr_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        corr_out_TVALID = 1'b1;
    end else begin
        corr_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln415_reg_363 == 1'd1))) begin
        max_val_ininout_tmp_0_out_ap_vld = 1'b1;
    end else begin
        max_val_ininout_tmp_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln415_reg_363 == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pow_s_blk_n = pow_s_empty_n;
    end else begin
        pow_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pow_s_read = 1'b1;
    end else begin
        pow_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln419_fu_313_p2 = (p_power_reg_372 + empty_fu_100);

assign add_ln430_fu_285_p2 = (tmp_fu_257_p4 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((corr_out_TREADY == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((corr_out_TREADY == 1'b0) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (pow_s_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (corr_out_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign best_fd_idx = p_fd_idx_reg_384;

assign best_tau = p_tau_reg_379;

assign corr_out_TDATA = out_data_reg_389;

assign corr_out_TKEEP = 4'd15;

assign corr_out_TLAST = out_last_reg_367_pp0_iter1_reg;

assign corr_out_TSTRB = 4'd15;

assign i_3_fu_216_p2 = (ap_sig_allocacmp_i_2 + 25'd1);

assign icmp_ln415_fu_210_p2 = ((ap_sig_allocacmp_i_2 == total) ? 1'b1 : 1'b0);

assign icmp_ln422_fu_318_p2 = (($signed(p_power_reg_372) > $signed(max_val_ininout_tmp_0_fu_104)) ? 1'b1 : 1'b0);

assign icmp_ln430_fu_279_p2 = ((trunc_ln430_fu_275_p1 == 32'd0) ? 1'b1 : 1'b0);

assign max_val_in_load_cast_cast_fu_188_p1 = max_val_in_load_cast;

assign max_val_ininout_tmp_0_out = max_val_ininout_tmp_0_fu_104;

assign out_data_fu_299_p3 = ((tmp_1_fu_267_p3[0:0] == 1'b1) ? select_ln430_fu_291_p3 : tmp_fu_257_p4);

assign out_last_fu_222_p2 = ((ap_sig_allocacmp_i_2 == sub) ? 1'b1 : 1'b0);

assign p_out = empty_fu_100;

assign p_power_fu_233_p1 = pow_s_dout[63:0];

assign select_ln430_fu_291_p3 = ((icmp_ln430_fu_279_p2[0:0] == 1'b1) ? tmp_fu_257_p4 : add_ln430_fu_285_p2);

assign sum_corr_in_load_cast_cast_fu_184_p1 = sum_corr_in_load_cast;

assign tmp_1_fu_267_p3 = pow_s_dout[32'd63];

assign tmp_fu_257_p4 = {{pow_s_dout[63:32]}};

assign trunc_ln430_fu_275_p1 = pow_s_dout[31:0];

endmodule //acquisition_serial_reduce_all_powers_Pipeline_REDUCE_ALL
