-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity acquisition_serial_m_axi_read_inputs_to_stream_m_axi is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_GMEM0_AWVALID : OUT STD_LOGIC;
    m_axi_GMEM0_AWREADY : IN STD_LOGIC;
    m_axi_GMEM0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_WVALID : OUT STD_LOGIC;
    m_axi_GMEM0_WREADY : IN STD_LOGIC;
    m_axi_GMEM0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_WLAST : OUT STD_LOGIC;
    m_axi_GMEM0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_ARVALID : OUT STD_LOGIC;
    m_axi_GMEM0_ARREADY : IN STD_LOGIC;
    m_axi_GMEM0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_RVALID : IN STD_LOGIC;
    m_axi_GMEM0_RREADY : OUT STD_LOGIC;
    m_axi_GMEM0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_RLAST : IN STD_LOGIC;
    m_axi_GMEM0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_GMEM0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_BVALID : IN STD_LOGIC;
    m_axi_GMEM0_BREADY : OUT STD_LOGIC;
    m_axi_GMEM0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    rx_real : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM1_AWVALID : OUT STD_LOGIC;
    m_axi_GMEM1_AWREADY : IN STD_LOGIC;
    m_axi_GMEM1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_WVALID : OUT STD_LOGIC;
    m_axi_GMEM1_WREADY : IN STD_LOGIC;
    m_axi_GMEM1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_WLAST : OUT STD_LOGIC;
    m_axi_GMEM1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_ARVALID : OUT STD_LOGIC;
    m_axi_GMEM1_ARREADY : IN STD_LOGIC;
    m_axi_GMEM1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_RVALID : IN STD_LOGIC;
    m_axi_GMEM1_RREADY : OUT STD_LOGIC;
    m_axi_GMEM1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_RLAST : IN STD_LOGIC;
    m_axi_GMEM1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_GMEM1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_BVALID : IN STD_LOGIC;
    m_axi_GMEM1_BREADY : OUT STD_LOGIC;
    m_axi_GMEM1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    prn_in : IN STD_LOGIC_VECTOR (63 downto 0);
    sig_s_din : OUT STD_LOGIC_VECTOR (1 downto 0);
    sig_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    sig_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    sig_s_full_n : IN STD_LOGIC;
    sig_s_write : OUT STD_LOGIC;
    prn_s_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    prn_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    prn_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    prn_s_full_n : IN STD_LOGIC;
    prn_s_write : OUT STD_LOGIC );
end;


architecture behav of acquisition_serial_m_axi_read_inputs_to_stream_m_axi is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2EDF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000010111011011111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal GMEM0_blk_n_AR : STD_LOGIC;
    signal GMEM1_blk_n_AR : STD_LOGIC;
    signal trunc_ln_fu_88_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln_reg_130 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal trunc_ln416_1_fu_109_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln416_1_reg_140 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_idle : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_ready : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWVALID : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WVALID : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WLAST : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARVALID : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_RREADY : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_BREADY : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWVALID : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WVALID : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WLAST : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARVALID : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_RREADY : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_BREADY : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_din : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_write : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_din : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_write : STD_LOGIC;
    signal grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal sext_ln416_fu_98_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln416_1_fu_119_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component acquisition_serial_m_axi_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_GMEM0_AWVALID : OUT STD_LOGIC;
        m_axi_GMEM0_AWREADY : IN STD_LOGIC;
        m_axi_GMEM0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_GMEM0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_WVALID : OUT STD_LOGIC;
        m_axi_GMEM0_WREADY : IN STD_LOGIC;
        m_axi_GMEM0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_WLAST : OUT STD_LOGIC;
        m_axi_GMEM0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_ARVALID : OUT STD_LOGIC;
        m_axi_GMEM0_ARREADY : IN STD_LOGIC;
        m_axi_GMEM0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_GMEM0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_RVALID : IN STD_LOGIC;
        m_axi_GMEM0_RREADY : OUT STD_LOGIC;
        m_axi_GMEM0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM0_RLAST : IN STD_LOGIC;
        m_axi_GMEM0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_GMEM0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM0_BVALID : IN STD_LOGIC;
        m_axi_GMEM0_BREADY : OUT STD_LOGIC;
        m_axi_GMEM0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_AWVALID : OUT STD_LOGIC;
        m_axi_GMEM1_AWREADY : IN STD_LOGIC;
        m_axi_GMEM1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_GMEM1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_WVALID : OUT STD_LOGIC;
        m_axi_GMEM1_WREADY : IN STD_LOGIC;
        m_axi_GMEM1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_WLAST : OUT STD_LOGIC;
        m_axi_GMEM1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_ARVALID : OUT STD_LOGIC;
        m_axi_GMEM1_ARREADY : IN STD_LOGIC;
        m_axi_GMEM1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_GMEM1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_GMEM1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_GMEM1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_RVALID : IN STD_LOGIC;
        m_axi_GMEM1_RREADY : OUT STD_LOGIC;
        m_axi_GMEM1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_GMEM1_RLAST : IN STD_LOGIC;
        m_axi_GMEM1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_GMEM1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM1_BVALID : IN STD_LOGIC;
        m_axi_GMEM1_BREADY : OUT STD_LOGIC;
        m_axi_GMEM1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_GMEM1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_GMEM1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sig_s_din : OUT STD_LOGIC_VECTOR (1 downto 0);
        sig_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        sig_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        sig_s_full_n : IN STD_LOGIC;
        sig_s_write : OUT STD_LOGIC;
        prn_s_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        prn_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        prn_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        prn_s_full_n : IN STD_LOGIC;
        prn_s_write : OUT STD_LOGIC;
        sext_ln416 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln416_1 : IN STD_LOGIC_VECTOR (61 downto 0) );
    end component;



begin
    grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74 : component acquisition_serial_m_axi_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start,
        ap_done => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done,
        ap_idle => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_idle,
        ap_ready => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_ready,
        m_axi_GMEM0_AWVALID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWVALID,
        m_axi_GMEM0_AWREADY => ap_const_logic_0,
        m_axi_GMEM0_AWADDR => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWADDR,
        m_axi_GMEM0_AWID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWID,
        m_axi_GMEM0_AWLEN => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWLEN,
        m_axi_GMEM0_AWSIZE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWSIZE,
        m_axi_GMEM0_AWBURST => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWBURST,
        m_axi_GMEM0_AWLOCK => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWLOCK,
        m_axi_GMEM0_AWCACHE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWCACHE,
        m_axi_GMEM0_AWPROT => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWPROT,
        m_axi_GMEM0_AWQOS => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWQOS,
        m_axi_GMEM0_AWREGION => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWREGION,
        m_axi_GMEM0_AWUSER => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_AWUSER,
        m_axi_GMEM0_WVALID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WVALID,
        m_axi_GMEM0_WREADY => ap_const_logic_0,
        m_axi_GMEM0_WDATA => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WDATA,
        m_axi_GMEM0_WSTRB => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WSTRB,
        m_axi_GMEM0_WLAST => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WLAST,
        m_axi_GMEM0_WID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WID,
        m_axi_GMEM0_WUSER => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_WUSER,
        m_axi_GMEM0_ARVALID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARVALID,
        m_axi_GMEM0_ARREADY => m_axi_GMEM0_ARREADY,
        m_axi_GMEM0_ARADDR => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARADDR,
        m_axi_GMEM0_ARID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARID,
        m_axi_GMEM0_ARLEN => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLEN,
        m_axi_GMEM0_ARSIZE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARSIZE,
        m_axi_GMEM0_ARBURST => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARBURST,
        m_axi_GMEM0_ARLOCK => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLOCK,
        m_axi_GMEM0_ARCACHE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARCACHE,
        m_axi_GMEM0_ARPROT => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARPROT,
        m_axi_GMEM0_ARQOS => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARQOS,
        m_axi_GMEM0_ARREGION => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARREGION,
        m_axi_GMEM0_ARUSER => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARUSER,
        m_axi_GMEM0_RVALID => m_axi_GMEM0_RVALID,
        m_axi_GMEM0_RREADY => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_RREADY,
        m_axi_GMEM0_RDATA => m_axi_GMEM0_RDATA,
        m_axi_GMEM0_RLAST => m_axi_GMEM0_RLAST,
        m_axi_GMEM0_RID => m_axi_GMEM0_RID,
        m_axi_GMEM0_RFIFONUM => m_axi_GMEM0_RFIFONUM,
        m_axi_GMEM0_RUSER => m_axi_GMEM0_RUSER,
        m_axi_GMEM0_RRESP => m_axi_GMEM0_RRESP,
        m_axi_GMEM0_BVALID => ap_const_logic_0,
        m_axi_GMEM0_BREADY => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_BREADY,
        m_axi_GMEM0_BRESP => ap_const_lv2_0,
        m_axi_GMEM0_BID => ap_const_lv1_0,
        m_axi_GMEM0_BUSER => ap_const_lv1_0,
        m_axi_GMEM1_AWVALID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWVALID,
        m_axi_GMEM1_AWREADY => ap_const_logic_0,
        m_axi_GMEM1_AWADDR => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWADDR,
        m_axi_GMEM1_AWID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWID,
        m_axi_GMEM1_AWLEN => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWLEN,
        m_axi_GMEM1_AWSIZE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWSIZE,
        m_axi_GMEM1_AWBURST => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWBURST,
        m_axi_GMEM1_AWLOCK => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWLOCK,
        m_axi_GMEM1_AWCACHE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWCACHE,
        m_axi_GMEM1_AWPROT => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWPROT,
        m_axi_GMEM1_AWQOS => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWQOS,
        m_axi_GMEM1_AWREGION => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWREGION,
        m_axi_GMEM1_AWUSER => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_AWUSER,
        m_axi_GMEM1_WVALID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WVALID,
        m_axi_GMEM1_WREADY => ap_const_logic_0,
        m_axi_GMEM1_WDATA => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WDATA,
        m_axi_GMEM1_WSTRB => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WSTRB,
        m_axi_GMEM1_WLAST => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WLAST,
        m_axi_GMEM1_WID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WID,
        m_axi_GMEM1_WUSER => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_WUSER,
        m_axi_GMEM1_ARVALID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARVALID,
        m_axi_GMEM1_ARREADY => m_axi_GMEM1_ARREADY,
        m_axi_GMEM1_ARADDR => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARADDR,
        m_axi_GMEM1_ARID => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARID,
        m_axi_GMEM1_ARLEN => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLEN,
        m_axi_GMEM1_ARSIZE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARSIZE,
        m_axi_GMEM1_ARBURST => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARBURST,
        m_axi_GMEM1_ARLOCK => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLOCK,
        m_axi_GMEM1_ARCACHE => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARCACHE,
        m_axi_GMEM1_ARPROT => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARPROT,
        m_axi_GMEM1_ARQOS => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARQOS,
        m_axi_GMEM1_ARREGION => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARREGION,
        m_axi_GMEM1_ARUSER => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARUSER,
        m_axi_GMEM1_RVALID => m_axi_GMEM1_RVALID,
        m_axi_GMEM1_RREADY => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_RREADY,
        m_axi_GMEM1_RDATA => m_axi_GMEM1_RDATA,
        m_axi_GMEM1_RLAST => m_axi_GMEM1_RLAST,
        m_axi_GMEM1_RID => m_axi_GMEM1_RID,
        m_axi_GMEM1_RFIFONUM => m_axi_GMEM1_RFIFONUM,
        m_axi_GMEM1_RUSER => m_axi_GMEM1_RUSER,
        m_axi_GMEM1_RRESP => m_axi_GMEM1_RRESP,
        m_axi_GMEM1_BVALID => ap_const_logic_0,
        m_axi_GMEM1_BREADY => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_BREADY,
        m_axi_GMEM1_BRESP => ap_const_lv2_0,
        m_axi_GMEM1_BID => ap_const_lv1_0,
        m_axi_GMEM1_BUSER => ap_const_lv1_0,
        sig_s_din => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_din,
        sig_s_num_data_valid => ap_const_lv7_0,
        sig_s_fifo_cap => ap_const_lv7_0,
        sig_s_full_n => sig_s_full_n,
        sig_s_write => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_write,
        prn_s_din => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_din,
        prn_s_num_data_valid => ap_const_lv7_0,
        prn_s_fifo_cap => ap_const_lv7_0,
        prn_s_full_n => prn_s_full_n,
        prn_s_write => grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_write,
        sext_ln416 => trunc_ln_reg_130,
        sext_ln416_1 => trunc_ln416_1_reg_140);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                trunc_ln416_1_reg_140 <= prn_in(63 downto 2);
                trunc_ln_reg_130 <= rx_real(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;

    GMEM0_blk_n_AR_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, m_axi_GMEM0_ARREADY)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            GMEM0_blk_n_AR <= m_axi_GMEM0_ARREADY;
        else 
            GMEM0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    GMEM1_blk_n_AR_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, m_axi_GMEM1_ARREADY)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            GMEM1_blk_n_AR <= m_axi_GMEM1_ARREADY;
        else 
            GMEM1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done)
    begin
        if ((grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1, ap_block_state1_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state1_io_assign_proc : process(m_axi_GMEM0_ARREADY, m_axi_GMEM1_ARREADY)
    begin
                ap_block_state1_io <= ((m_axi_GMEM0_ARREADY = ap_const_logic_0) or (m_axi_GMEM1_ARREADY = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_start_reg;

    internal_ap_ready_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_GMEM0_ARADDR_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARADDR, ap_CS_fsm_state9, ap_CS_fsm_state10, sext_ln416_fu_98_p1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_GMEM0_ARADDR <= sext_ln416_fu_98_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARADDR <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARADDR;
        else 
            m_axi_GMEM0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_GMEM0_ARBURST_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARBURST, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARBURST <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARBURST;
        else 
            m_axi_GMEM0_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_GMEM0_ARCACHE_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARCACHE, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARCACHE <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARCACHE;
        else 
            m_axi_GMEM0_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_GMEM0_ARID_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARID, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARID <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARID;
        else 
            m_axi_GMEM0_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_GMEM0_ARLEN_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLEN, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_GMEM0_ARLEN <= ap_const_lv32_2EDF;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARLEN <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLEN;
        else 
            m_axi_GMEM0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_GMEM0_ARLOCK_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLOCK, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARLOCK <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARLOCK;
        else 
            m_axi_GMEM0_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_GMEM0_ARPROT_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARPROT, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARPROT <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARPROT;
        else 
            m_axi_GMEM0_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_GMEM0_ARQOS_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARQOS, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARQOS <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARQOS;
        else 
            m_axi_GMEM0_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_GMEM0_ARREGION_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARREGION, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARREGION <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARREGION;
        else 
            m_axi_GMEM0_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_GMEM0_ARSIZE_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARSIZE, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARSIZE <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARSIZE;
        else 
            m_axi_GMEM0_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_GMEM0_ARUSER_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARUSER, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARUSER <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARUSER;
        else 
            m_axi_GMEM0_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_GMEM0_ARVALID_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARVALID, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_GMEM0_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_ARVALID <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_ARVALID;
        else 
            m_axi_GMEM0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_GMEM0_AWADDR <= ap_const_lv64_0;
    m_axi_GMEM0_AWBURST <= ap_const_lv2_0;
    m_axi_GMEM0_AWCACHE <= ap_const_lv4_0;
    m_axi_GMEM0_AWID <= ap_const_lv1_0;
    m_axi_GMEM0_AWLEN <= ap_const_lv32_0;
    m_axi_GMEM0_AWLOCK <= ap_const_lv2_0;
    m_axi_GMEM0_AWPROT <= ap_const_lv3_0;
    m_axi_GMEM0_AWQOS <= ap_const_lv4_0;
    m_axi_GMEM0_AWREGION <= ap_const_lv4_0;
    m_axi_GMEM0_AWSIZE <= ap_const_lv3_0;
    m_axi_GMEM0_AWUSER <= ap_const_lv1_0;
    m_axi_GMEM0_AWVALID <= ap_const_logic_0;
    m_axi_GMEM0_BREADY <= ap_const_logic_0;

    m_axi_GMEM0_RREADY_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_RREADY, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM0_RREADY <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM0_RREADY;
        else 
            m_axi_GMEM0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_GMEM0_WDATA <= ap_const_lv32_0;
    m_axi_GMEM0_WID <= ap_const_lv1_0;
    m_axi_GMEM0_WLAST <= ap_const_logic_0;
    m_axi_GMEM0_WSTRB <= ap_const_lv4_0;
    m_axi_GMEM0_WUSER <= ap_const_lv1_0;
    m_axi_GMEM0_WVALID <= ap_const_logic_0;

    m_axi_GMEM1_ARADDR_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARADDR, ap_CS_fsm_state9, ap_CS_fsm_state10, sext_ln416_1_fu_119_p1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_GMEM1_ARADDR <= sext_ln416_1_fu_119_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARADDR <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARADDR;
        else 
            m_axi_GMEM1_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_GMEM1_ARBURST_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARBURST, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARBURST <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARBURST;
        else 
            m_axi_GMEM1_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_GMEM1_ARCACHE_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARCACHE, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARCACHE <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARCACHE;
        else 
            m_axi_GMEM1_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_GMEM1_ARID_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARID, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARID <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARID;
        else 
            m_axi_GMEM1_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_GMEM1_ARLEN_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLEN, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_GMEM1_ARLEN <= ap_const_lv32_2EDF;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARLEN <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLEN;
        else 
            m_axi_GMEM1_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_GMEM1_ARLOCK_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLOCK, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARLOCK <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARLOCK;
        else 
            m_axi_GMEM1_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_GMEM1_ARPROT_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARPROT, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARPROT <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARPROT;
        else 
            m_axi_GMEM1_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_GMEM1_ARQOS_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARQOS, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARQOS <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARQOS;
        else 
            m_axi_GMEM1_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_GMEM1_ARREGION_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARREGION, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARREGION <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARREGION;
        else 
            m_axi_GMEM1_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_GMEM1_ARSIZE_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARSIZE, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARSIZE <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARSIZE;
        else 
            m_axi_GMEM1_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_GMEM1_ARUSER_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARUSER, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARUSER <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARUSER;
        else 
            m_axi_GMEM1_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_GMEM1_ARVALID_assign_proc : process(ap_CS_fsm_state1, ap_block_state1, ap_block_state1_io, grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARVALID, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_io) or (ap_const_boolean_1 = ap_block_state1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_GMEM1_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_ARVALID <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_ARVALID;
        else 
            m_axi_GMEM1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_GMEM1_AWADDR <= ap_const_lv64_0;
    m_axi_GMEM1_AWBURST <= ap_const_lv2_0;
    m_axi_GMEM1_AWCACHE <= ap_const_lv4_0;
    m_axi_GMEM1_AWID <= ap_const_lv1_0;
    m_axi_GMEM1_AWLEN <= ap_const_lv32_0;
    m_axi_GMEM1_AWLOCK <= ap_const_lv2_0;
    m_axi_GMEM1_AWPROT <= ap_const_lv3_0;
    m_axi_GMEM1_AWQOS <= ap_const_lv4_0;
    m_axi_GMEM1_AWREGION <= ap_const_lv4_0;
    m_axi_GMEM1_AWSIZE <= ap_const_lv3_0;
    m_axi_GMEM1_AWUSER <= ap_const_lv1_0;
    m_axi_GMEM1_AWVALID <= ap_const_logic_0;
    m_axi_GMEM1_BREADY <= ap_const_logic_0;

    m_axi_GMEM1_RREADY_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_RREADY, ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            m_axi_GMEM1_RREADY <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_m_axi_GMEM1_RREADY;
        else 
            m_axi_GMEM1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_GMEM1_WDATA <= ap_const_lv32_0;
    m_axi_GMEM1_WID <= ap_const_lv1_0;
    m_axi_GMEM1_WLAST <= ap_const_logic_0;
    m_axi_GMEM1_WSTRB <= ap_const_lv4_0;
    m_axi_GMEM1_WUSER <= ap_const_lv1_0;
    m_axi_GMEM1_WVALID <= ap_const_logic_0;
    prn_s_din <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_din;

    prn_s_write_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_write, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            prn_s_write <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_prn_s_write;
        else 
            prn_s_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln416_1_fu_119_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln416_1_fu_109_p4),64));

        sext_ln416_fu_98_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_88_p4),64));

    sig_s_din <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_din;

    sig_s_write_assign_proc : process(grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_write, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            sig_s_write <= grp_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS_fu_74_sig_s_write;
        else 
            sig_s_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln416_1_fu_109_p4 <= prn_in(63 downto 2);
    trunc_ln_fu_88_p4 <= rx_real(63 downto 2);
end behav;
