-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity acquisition_serial_m_axi_process_tau_df_v9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mixI_loc_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    mixI_loc_0_ce0 : OUT STD_LOGIC;
    mixI_loc_0_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    mixI_loc_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    mixI_loc_1_ce0 : OUT STD_LOGIC;
    mixI_loc_1_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
    mixQ_loc_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    mixQ_loc_0_ce0 : OUT STD_LOGIC;
    mixQ_loc_0_q0 : IN STD_LOGIC_VECTOR (18 downto 0);
    mixQ_loc_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    mixQ_loc_1_ce0 : OUT STD_LOGIC;
    mixQ_loc_1_q0 : IN STD_LOGIC_VECTOR (18 downto 0);
    pow_s_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    pow_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    pow_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    pow_s_full_n : IN STD_LOGIC;
    pow_s_write : OUT STD_LOGIC;
    fd_idx : IN STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 : OUT STD_LOGIC;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of acquisition_serial_m_axi_process_tau_df_v9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv11_8 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln642_fu_130_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln642_reg_161 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_process_tau_tile_v9_fu_76_ap_start : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_ap_done : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_ap_idle : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_ap_ready : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_mixI_loc_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_process_tau_tile_v9_fu_76_mixI_loc_0_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_mixI_loc_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_process_tau_tile_v9_fu_76_mixI_loc_1_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_mixQ_loc_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_process_tau_tile_v9_fu_76_mixQ_loc_0_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_mixQ_loc_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_process_tau_tile_v9_fu_76_mixQ_loc_1_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_pow_s_din : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_process_tau_tile_v9_fu_76_pow_s_write : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 : STD_LOGIC;
    signal grp_process_tau_tile_v9_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln642_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tau_base_fu_66 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal tau_base_3_fu_135_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component acquisition_serial_m_axi_process_tau_tile_v9 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mixI_loc_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        mixI_loc_0_ce0 : OUT STD_LOGIC;
        mixI_loc_0_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        mixI_loc_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        mixI_loc_1_ce0 : OUT STD_LOGIC;
        mixI_loc_1_q0 : IN STD_LOGIC_VECTOR (19 downto 0);
        mixQ_loc_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        mixQ_loc_0_ce0 : OUT STD_LOGIC;
        mixQ_loc_0_q0 : IN STD_LOGIC_VECTOR (18 downto 0);
        mixQ_loc_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        mixQ_loc_1_ce0 : OUT STD_LOGIC;
        mixQ_loc_1_q0 : IN STD_LOGIC_VECTOR (18 downto 0);
        pow_s_din : OUT STD_LOGIC_VECTOR (127 downto 0);
        pow_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        pow_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        pow_s_full_n : IN STD_LOGIC;
        pow_s_write : OUT STD_LOGIC;
        fd_idx : IN STD_LOGIC_VECTOR (14 downto 0);
        tau_base : IN STD_LOGIC_VECTOR (9 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 : OUT STD_LOGIC;
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_process_tau_tile_v9_fu_76 : component acquisition_serial_m_axi_process_tau_tile_v9
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_process_tau_tile_v9_fu_76_ap_start,
        ap_done => grp_process_tau_tile_v9_fu_76_ap_done,
        ap_idle => grp_process_tau_tile_v9_fu_76_ap_idle,
        ap_ready => grp_process_tau_tile_v9_fu_76_ap_ready,
        mixI_loc_0_address0 => grp_process_tau_tile_v9_fu_76_mixI_loc_0_address0,
        mixI_loc_0_ce0 => grp_process_tau_tile_v9_fu_76_mixI_loc_0_ce0,
        mixI_loc_0_q0 => mixI_loc_0_q0,
        mixI_loc_1_address0 => grp_process_tau_tile_v9_fu_76_mixI_loc_1_address0,
        mixI_loc_1_ce0 => grp_process_tau_tile_v9_fu_76_mixI_loc_1_ce0,
        mixI_loc_1_q0 => mixI_loc_1_q0,
        mixQ_loc_0_address0 => grp_process_tau_tile_v9_fu_76_mixQ_loc_0_address0,
        mixQ_loc_0_ce0 => grp_process_tau_tile_v9_fu_76_mixQ_loc_0_ce0,
        mixQ_loc_0_q0 => mixQ_loc_0_q0,
        mixQ_loc_1_address0 => grp_process_tau_tile_v9_fu_76_mixQ_loc_1_address0,
        mixQ_loc_1_ce0 => grp_process_tau_tile_v9_fu_76_mixQ_loc_1_ce0,
        mixQ_loc_1_q0 => mixQ_loc_1_q0,
        pow_s_din => grp_process_tau_tile_v9_fu_76_pow_s_din,
        pow_s_num_data_valid => ap_const_lv7_0,
        pow_s_fifo_cap => ap_const_lv7_0,
        pow_s_full_n => pow_s_full_n,
        pow_s_write => grp_process_tau_tile_v9_fu_76_pow_s_write,
        fd_idx => fd_idx,
        tau_base => trunc_ln642_reg_161,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 => grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_q0 => acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_process_tau_tile_v9_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_process_tau_tile_v9_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln642_fu_124_p2 = ap_const_lv1_1))) then 
                    grp_process_tau_tile_v9_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_process_tau_tile_v9_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_process_tau_tile_v9_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    tau_base_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                tau_base_fu_66 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln642_fu_124_p2 = ap_const_lv1_1))) then 
                tau_base_fu_66 <= tau_base_3_fu_135_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln642_reg_161 <= trunc_ln642_fu_130_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_process_tau_tile_v9_fu_76_ap_done, icmp_ln642_fu_124_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln642_fu_124_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_process_tau_tile_v9_fu_76_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0;
    acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 <= grp_process_tau_tile_v9_fu_76_acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_process_tau_tile_v9_fu_76_ap_done)
    begin
        if ((grp_process_tau_tile_v9_fu_76_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln642_fu_124_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln642_fu_124_p2 = ap_const_lv1_0)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln642_fu_124_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln642_fu_124_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_process_tau_tile_v9_fu_76_ap_start <= grp_process_tau_tile_v9_fu_76_ap_start_reg;
    icmp_ln642_fu_124_p2 <= "1" when (unsigned(tau_base_fu_66) < unsigned(ap_const_lv11_3FF)) else "0";
    mixI_loc_0_address0 <= grp_process_tau_tile_v9_fu_76_mixI_loc_0_address0;
    mixI_loc_0_ce0 <= grp_process_tau_tile_v9_fu_76_mixI_loc_0_ce0;
    mixI_loc_1_address0 <= grp_process_tau_tile_v9_fu_76_mixI_loc_1_address0;
    mixI_loc_1_ce0 <= grp_process_tau_tile_v9_fu_76_mixI_loc_1_ce0;
    mixQ_loc_0_address0 <= grp_process_tau_tile_v9_fu_76_mixQ_loc_0_address0;
    mixQ_loc_0_ce0 <= grp_process_tau_tile_v9_fu_76_mixQ_loc_0_ce0;
    mixQ_loc_1_address0 <= grp_process_tau_tile_v9_fu_76_mixQ_loc_1_address0;
    mixQ_loc_1_ce0 <= grp_process_tau_tile_v9_fu_76_mixQ_loc_1_ce0;
    pow_s_din <= grp_process_tau_tile_v9_fu_76_pow_s_din;

    pow_s_write_assign_proc : process(grp_process_tau_tile_v9_fu_76_pow_s_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            pow_s_write <= grp_process_tau_tile_v9_fu_76_pow_s_write;
        else 
            pow_s_write <= ap_const_logic_0;
        end if; 
    end process;

    tau_base_3_fu_135_p2 <= std_logic_vector(unsigned(tau_base_fu_66) + unsigned(ap_const_lv11_8));
    trunc_ln642_fu_130_p1 <= tau_base_fu_66(10 - 1 downto 0);
end behav;
