-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity acquisition_serial_m_axi_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_GMEM0_AWVALID : OUT STD_LOGIC;
    m_axi_GMEM0_AWREADY : IN STD_LOGIC;
    m_axi_GMEM0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_WVALID : OUT STD_LOGIC;
    m_axi_GMEM0_WREADY : IN STD_LOGIC;
    m_axi_GMEM0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_WLAST : OUT STD_LOGIC;
    m_axi_GMEM0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_ARVALID : OUT STD_LOGIC;
    m_axi_GMEM0_ARREADY : IN STD_LOGIC;
    m_axi_GMEM0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_RVALID : IN STD_LOGIC;
    m_axi_GMEM0_RREADY : OUT STD_LOGIC;
    m_axi_GMEM0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM0_RLAST : IN STD_LOGIC;
    m_axi_GMEM0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_GMEM0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_BVALID : IN STD_LOGIC;
    m_axi_GMEM0_BREADY : OUT STD_LOGIC;
    m_axi_GMEM0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_AWVALID : OUT STD_LOGIC;
    m_axi_GMEM1_AWREADY : IN STD_LOGIC;
    m_axi_GMEM1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_WVALID : OUT STD_LOGIC;
    m_axi_GMEM1_WREADY : IN STD_LOGIC;
    m_axi_GMEM1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_WLAST : OUT STD_LOGIC;
    m_axi_GMEM1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_ARVALID : OUT STD_LOGIC;
    m_axi_GMEM1_ARREADY : IN STD_LOGIC;
    m_axi_GMEM1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_GMEM1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_RVALID : IN STD_LOGIC;
    m_axi_GMEM1_RREADY : OUT STD_LOGIC;
    m_axi_GMEM1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_GMEM1_RLAST : IN STD_LOGIC;
    m_axi_GMEM1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_GMEM1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_BVALID : IN STD_LOGIC;
    m_axi_GMEM1_BREADY : OUT STD_LOGIC;
    m_axi_GMEM1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_GMEM1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sig_s_din : OUT STD_LOGIC_VECTOR (1 downto 0);
    sig_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    sig_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    sig_s_full_n : IN STD_LOGIC;
    sig_s_write : OUT STD_LOGIC;
    prn_s_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    prn_s_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    prn_s_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    prn_s_full_n : IN STD_LOGIC;
    prn_s_write : OUT STD_LOGIC;
    sext_ln416 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln416_1 : IN STD_LOGIC_VECTOR (61 downto 0) );
end;


architecture behav of acquisition_serial_m_axi_read_inputs_to_stream_m_axi_Pipeline_READ_INPUTS is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_2EDF : STD_LOGIC_VECTOR (13 downto 0) := "10111011011111";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln416_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal GMEM0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal GMEM1_blk_n_R : STD_LOGIC;
    signal sig_s_blk_n : STD_LOGIC;
    signal prn_s_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal prnw_reg_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln421_fu_145_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln421_reg_181 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_fu_60 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln416_fu_122_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component acquisition_serial_m_axi_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component acquisition_serial_m_axi_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln416_fu_116_p2 = ap_const_lv1_0))) then 
                    i_fu_60 <= add_ln416_fu_122_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_60 <= ap_const_lv14_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                prnw_reg_176 <= m_axi_GMEM1_RDATA;
                trunc_ln421_reg_181 <= trunc_ln421_fu_145_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    GMEM0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_GMEM0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            GMEM0_blk_n_R <= m_axi_GMEM0_RVALID;
        else 
            GMEM0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    GMEM1_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_GMEM1_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            GMEM1_blk_n_R <= m_axi_GMEM1_RVALID;
        else 
            GMEM1_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    add_ln416_fu_122_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv14_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_GMEM0_RVALID, m_axi_GMEM1_RVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((m_axi_GMEM0_RVALID = ap_const_logic_0) or (m_axi_GMEM1_RVALID = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(sig_s_full_n, prn_s_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((prn_s_full_n = ap_const_logic_0) or (sig_s_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln416_fu_116_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln416_fu_116_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_60, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv14_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_60;
        end if; 
    end process;

    icmp_ln416_fu_116_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv14_2EDF) else "0";
    m_axi_GMEM0_ARADDR <= ap_const_lv64_0;
    m_axi_GMEM0_ARBURST <= ap_const_lv2_0;
    m_axi_GMEM0_ARCACHE <= ap_const_lv4_0;
    m_axi_GMEM0_ARID <= ap_const_lv1_0;
    m_axi_GMEM0_ARLEN <= ap_const_lv32_0;
    m_axi_GMEM0_ARLOCK <= ap_const_lv2_0;
    m_axi_GMEM0_ARPROT <= ap_const_lv3_0;
    m_axi_GMEM0_ARQOS <= ap_const_lv4_0;
    m_axi_GMEM0_ARREGION <= ap_const_lv4_0;
    m_axi_GMEM0_ARSIZE <= ap_const_lv3_0;
    m_axi_GMEM0_ARUSER <= ap_const_lv1_0;
    m_axi_GMEM0_ARVALID <= ap_const_logic_0;
    m_axi_GMEM0_AWADDR <= ap_const_lv64_0;
    m_axi_GMEM0_AWBURST <= ap_const_lv2_0;
    m_axi_GMEM0_AWCACHE <= ap_const_lv4_0;
    m_axi_GMEM0_AWID <= ap_const_lv1_0;
    m_axi_GMEM0_AWLEN <= ap_const_lv32_0;
    m_axi_GMEM0_AWLOCK <= ap_const_lv2_0;
    m_axi_GMEM0_AWPROT <= ap_const_lv3_0;
    m_axi_GMEM0_AWQOS <= ap_const_lv4_0;
    m_axi_GMEM0_AWREGION <= ap_const_lv4_0;
    m_axi_GMEM0_AWSIZE <= ap_const_lv3_0;
    m_axi_GMEM0_AWUSER <= ap_const_lv1_0;
    m_axi_GMEM0_AWVALID <= ap_const_logic_0;
    m_axi_GMEM0_BREADY <= ap_const_logic_0;

    m_axi_GMEM0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_GMEM0_RREADY <= ap_const_logic_1;
        else 
            m_axi_GMEM0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_GMEM0_WDATA <= ap_const_lv32_0;
    m_axi_GMEM0_WID <= ap_const_lv1_0;
    m_axi_GMEM0_WLAST <= ap_const_logic_0;
    m_axi_GMEM0_WSTRB <= ap_const_lv4_0;
    m_axi_GMEM0_WUSER <= ap_const_lv1_0;
    m_axi_GMEM0_WVALID <= ap_const_logic_0;
    m_axi_GMEM1_ARADDR <= ap_const_lv64_0;
    m_axi_GMEM1_ARBURST <= ap_const_lv2_0;
    m_axi_GMEM1_ARCACHE <= ap_const_lv4_0;
    m_axi_GMEM1_ARID <= ap_const_lv1_0;
    m_axi_GMEM1_ARLEN <= ap_const_lv32_0;
    m_axi_GMEM1_ARLOCK <= ap_const_lv2_0;
    m_axi_GMEM1_ARPROT <= ap_const_lv3_0;
    m_axi_GMEM1_ARQOS <= ap_const_lv4_0;
    m_axi_GMEM1_ARREGION <= ap_const_lv4_0;
    m_axi_GMEM1_ARSIZE <= ap_const_lv3_0;
    m_axi_GMEM1_ARUSER <= ap_const_lv1_0;
    m_axi_GMEM1_ARVALID <= ap_const_logic_0;
    m_axi_GMEM1_AWADDR <= ap_const_lv64_0;
    m_axi_GMEM1_AWBURST <= ap_const_lv2_0;
    m_axi_GMEM1_AWCACHE <= ap_const_lv4_0;
    m_axi_GMEM1_AWID <= ap_const_lv1_0;
    m_axi_GMEM1_AWLEN <= ap_const_lv32_0;
    m_axi_GMEM1_AWLOCK <= ap_const_lv2_0;
    m_axi_GMEM1_AWPROT <= ap_const_lv3_0;
    m_axi_GMEM1_AWQOS <= ap_const_lv4_0;
    m_axi_GMEM1_AWREGION <= ap_const_lv4_0;
    m_axi_GMEM1_AWSIZE <= ap_const_lv3_0;
    m_axi_GMEM1_AWUSER <= ap_const_lv1_0;
    m_axi_GMEM1_AWVALID <= ap_const_logic_0;
    m_axi_GMEM1_BREADY <= ap_const_logic_0;

    m_axi_GMEM1_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_GMEM1_RREADY <= ap_const_logic_1;
        else 
            m_axi_GMEM1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_GMEM1_WDATA <= ap_const_lv32_0;
    m_axi_GMEM1_WID <= ap_const_lv1_0;
    m_axi_GMEM1_WLAST <= ap_const_logic_0;
    m_axi_GMEM1_WSTRB <= ap_const_lv4_0;
    m_axi_GMEM1_WUSER <= ap_const_lv1_0;
    m_axi_GMEM1_WVALID <= ap_const_logic_0;

    prn_s_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, prn_s_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            prn_s_blk_n <= prn_s_full_n;
        else 
            prn_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    prn_s_din <= "1" when (signed(prnw_reg_176) > signed(ap_const_lv32_0)) else "0";

    prn_s_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            prn_s_write <= ap_const_logic_1;
        else 
            prn_s_write <= ap_const_logic_0;
        end if; 
    end process;


    sig_s_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, sig_s_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            sig_s_blk_n <= sig_s_full_n;
        else 
            sig_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sig_s_din <= trunc_ln421_reg_181;

    sig_s_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            sig_s_write <= ap_const_logic_1;
        else 
            sig_s_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln421_fu_145_p1 <= m_axi_GMEM0_RDATA(2 - 1 downto 0);
end behav;
