-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity acquisition_stsa_top_select_spaced_topk_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    top_in_doppler_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    top_in_doppler_ce0 : OUT STD_LOGIC;
    top_in_doppler_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    top_in_doppler_offset : IN STD_LOGIC_VECTOR (63 downto 0);
    top_in_phase_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    top_in_phase_ce0 : OUT STD_LOGIC;
    top_in_phase_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    top_in_phase_offset : IN STD_LOGIC_VECTOR (63 downto 0);
    top_in_power_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    top_in_power_ce0 : OUT STD_LOGIC;
    top_in_power_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    top_in_power_offset : IN STD_LOGIC_VECTOR (63 downto 0);
    n_top_in : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (23 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of acquisition_stsa_top_select_spaced_topk_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv30_1 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_1274_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_reg_2745 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_9_fu_1286_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_9_reg_2750 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_fu_1298_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_reg_2755 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_2_fu_1315_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal r_2_reg_2764 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_11_fu_1826_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_2769 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal empty_126_fu_1839_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_126_reg_2773 : STD_LOGIC_VECTOR (5 downto 0);
    signal top_in_phase_load_reg_2788 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal top_in_doppler_load_reg_2809 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_0_0_load_reg_2830 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal out_spaced_doppler_1_0_load_reg_2835 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_2_0_load_reg_2840 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_3_0_load_reg_2845 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_4_0_load_reg_2850 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_5_0_load_reg_2855 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_6_0_load_reg_2860 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_7_0_load_reg_2865 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_8_0_load_reg_2870 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_9_0_load_reg_2875 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_10_0_load_reg_2880 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_11_0_load_reg_2885 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_1214_0_load_reg_2890 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_13_0_load_reg_2895 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_14_0_load_reg_2900 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_doppler_15_0_load_reg_2905 : STD_LOGIC_VECTOR (23 downto 0);
    signal out_spaced_phase_0_0_load_reg_2910 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_1_0_load_reg_2915 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_15_0_load_reg_2920 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_14_0_load_reg_2925 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_13_0_load_reg_2930 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_12_0_load_reg_2935 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_11_0_load_reg_2940 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_10_0_load_reg_2945 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_9_0_load_reg_2950 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_8_0_load_reg_2955 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_7_0_load_reg_2960 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_6_0_load_reg_2965 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_5_0_load_reg_2970 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_4_0_load_reg_2975 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_3_0_load_reg_2980 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_spaced_phase_2_0_load_reg_2985 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_load_1_reg_2990 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln5016_fu_1873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln5016_reg_2996 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln5016_fu_1882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln5016_reg_3001 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal trunc_ln5017_1_fu_1896_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln5017_1_reg_3010 : STD_LOGIC_VECTOR (3 downto 0);
    signal used_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal used_ce0 : STD_LOGIC;
    signal used_we0 : STD_LOGIC;
    signal used_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal used_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_done : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_idle : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_ready : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_ce0 : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_we0 : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_done : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_idle : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_ready : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_ce0 : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_ce0 : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out_ap_vld : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_done : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_idle : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_ready : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_far_enough_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_far_enough_out_ap_vld : STD_LOGIC;
    signal grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start_reg : STD_LOGIC := '0';
    signal grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln4986_fu_1309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal p_cast_fu_1848_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast53_fu_1858_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom32_fu_1834_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln5017_fu_1891_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_192 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal out_spaced_doppler_0_0_fu_196 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal out_spaced_doppler_1_0_fu_200 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal out_spaced_power_15_049_fu_204 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_2_0_fu_208 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag79_0_fu_212 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_14_050_fu_216 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_3_0_fu_220 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag76_0_fu_224 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_13_051_fu_228 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_4_0_fu_232 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag73_0_fu_236 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_12_052_fu_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_5_0_fu_244 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag70_0_fu_248 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_11_053_fu_252 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_6_0_fu_256 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag67_0_fu_260 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_10_054_fu_264 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_7_0_fu_268 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag64_0_fu_272 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_9_055_fu_276 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_8_0_fu_280 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag61_0_fu_284 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_8_056_fu_288 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_9_0_fu_292 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag58_0_fu_296 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_7_057_fu_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_10_0_fu_304 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag55_0_fu_308 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_6_058_fu_312 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_11_0_fu_316 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag52_0_fu_320 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_5_059_fu_324 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_1214_0_fu_328 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag49_0_fu_332 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_4_060_fu_336 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_13_0_fu_340 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag46_0_fu_344 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_3_061_fu_348 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_14_0_fu_352 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag43_0_fu_356 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_2_062_fu_360 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_doppler_15_0_fu_364 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal write_flag40_0_fu_368 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_1_063_fu_372 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_0_0_fu_376 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal write_flag37_0_fu_380 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_power_0_064_fu_384 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_1_0_fu_388 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal write_flag_0_fu_392 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal out_spaced_phase_15_0_fu_396 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_14_0_fu_400 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_13_0_fu_404 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_12_0_fu_408 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_11_0_fu_412 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_10_0_fu_416 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_9_0_fu_420 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_8_0_fu_424 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_7_0_fu_428 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_6_0_fu_432 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_5_0_fu_436 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_4_0_fu_440 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_3_0_fu_444 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal out_spaced_phase_2_0_fu_448 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal count_fu_452 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal count_1_fu_2187_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_1270_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_125_fu_1282_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln5017_fu_1294_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln5024_fu_1417_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_1_fu_1424_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_2_fu_1431_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_3_fu_1438_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_4_fu_1445_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_5_fu_1452_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_6_fu_1459_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_7_fu_1466_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_8_fu_1473_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_9_fu_1480_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_10_fu_1487_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_11_fu_1494_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_12_fu_1501_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_13_fu_1508_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_14_fu_1515_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln5024_15_fu_1522_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_127_fu_1843_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_128_fu_1853_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_12_fu_1863_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln5017_fu_1887_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component acquisition_stsa_top_select_spaced_topk_1_Pipeline_INIT_USED IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        used_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        used_ce0 : OUT STD_LOGIC;
        used_we0 : OUT STD_LOGIC;
        used_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component acquisition_stsa_top_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        n_top_in : IN STD_LOGIC_VECTOR (31 downto 0);
        used_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        used_ce0 : OUT STD_LOGIC;
        used_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (5 downto 0);
        top_in_power_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        top_in_power_ce0 : OUT STD_LOGIC;
        top_in_power_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        best_idx_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        best_idx_out_ap_vld : OUT STD_LOGIC );
    end component;


    component acquisition_stsa_top_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_spaced_phase_0_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_1_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_2_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_3_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_4_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_5_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_6_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_7_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_8_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_9_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_10_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_11_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_12_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_13_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_14_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_phase_15_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        top_in_phase_load : IN STD_LOGIC_VECTOR (31 downto 0);
        out_spaced_doppler_0_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_1_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_2_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_3_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_4_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_5_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_6_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_7_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_8_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_9_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_10_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_11_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_1214_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_13_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_14_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        out_spaced_doppler_15_0 : IN STD_LOGIC_VECTOR (23 downto 0);
        sext_ln5003 : IN STD_LOGIC_VECTOR (23 downto 0);
        count : IN STD_LOGIC_VECTOR (31 downto 0);
        far_enough_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        far_enough_out_ap_vld : OUT STD_LOGIC );
    end component;


    component acquisition_stsa_top_select_spaced_topk_used_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    used_U : component acquisition_stsa_top_select_spaced_topk_used_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => used_address0,
        ce0 => used_ce0,
        we0 => used_we0,
        d0 => used_d0,
        q0 => used_q0);

    grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832 : component acquisition_stsa_top_select_spaced_topk_1_Pipeline_INIT_USED
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start,
        ap_done => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_done,
        ap_idle => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_idle,
        ap_ready => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_ready,
        used_address0 => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_address0,
        used_ce0 => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_ce0,
        used_we0 => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_we0,
        used_d0 => grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_d0);

    grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838 : component acquisition_stsa_top_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start,
        ap_done => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_done,
        ap_idle => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_idle,
        ap_ready => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_ready,
        n_top_in => n_top_in,
        used_address0 => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_address0,
        used_ce0 => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_ce0,
        used_q0 => used_q0,
        empty => tmp_10_reg_2755,
        top_in_power_address0 => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_address0,
        top_in_power_ce0 => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_ce0,
        top_in_power_q0 => top_in_power_q0,
        best_idx_out => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out,
        best_idx_out_ap_vld => grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out_ap_vld);

    grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848 : component acquisition_stsa_top_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start,
        ap_done => grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_done,
        ap_idle => grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_idle,
        ap_ready => grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_ready,
        out_spaced_phase_0_0 => out_spaced_phase_0_0_load_reg_2910,
        out_spaced_phase_1_0 => out_spaced_phase_1_0_load_reg_2915,
        out_spaced_phase_2_0 => out_spaced_phase_2_0_load_reg_2985,
        out_spaced_phase_3_0 => out_spaced_phase_3_0_load_reg_2980,
        out_spaced_phase_4_0 => out_spaced_phase_4_0_load_reg_2975,
        out_spaced_phase_5_0 => out_spaced_phase_5_0_load_reg_2970,
        out_spaced_phase_6_0 => out_spaced_phase_6_0_load_reg_2965,
        out_spaced_phase_7_0 => out_spaced_phase_7_0_load_reg_2960,
        out_spaced_phase_8_0 => out_spaced_phase_8_0_load_reg_2955,
        out_spaced_phase_9_0 => out_spaced_phase_9_0_load_reg_2950,
        out_spaced_phase_10_0 => out_spaced_phase_10_0_load_reg_2945,
        out_spaced_phase_11_0 => out_spaced_phase_11_0_load_reg_2940,
        out_spaced_phase_12_0 => out_spaced_phase_12_0_load_reg_2935,
        out_spaced_phase_13_0 => out_spaced_phase_13_0_load_reg_2930,
        out_spaced_phase_14_0 => out_spaced_phase_14_0_load_reg_2925,
        out_spaced_phase_15_0 => out_spaced_phase_15_0_load_reg_2920,
        top_in_phase_load => top_in_phase_load_reg_2788,
        out_spaced_doppler_0_0 => out_spaced_doppler_0_0_load_reg_2830,
        out_spaced_doppler_1_0 => out_spaced_doppler_1_0_load_reg_2835,
        out_spaced_doppler_2_0 => out_spaced_doppler_2_0_load_reg_2840,
        out_spaced_doppler_3_0 => out_spaced_doppler_3_0_load_reg_2845,
        out_spaced_doppler_4_0 => out_spaced_doppler_4_0_load_reg_2850,
        out_spaced_doppler_5_0 => out_spaced_doppler_5_0_load_reg_2855,
        out_spaced_doppler_6_0 => out_spaced_doppler_6_0_load_reg_2860,
        out_spaced_doppler_7_0 => out_spaced_doppler_7_0_load_reg_2865,
        out_spaced_doppler_8_0 => out_spaced_doppler_8_0_load_reg_2870,
        out_spaced_doppler_9_0 => out_spaced_doppler_9_0_load_reg_2875,
        out_spaced_doppler_10_0 => out_spaced_doppler_10_0_load_reg_2880,
        out_spaced_doppler_11_0 => out_spaced_doppler_11_0_load_reg_2885,
        out_spaced_doppler_1214_0 => out_spaced_doppler_1214_0_load_reg_2890,
        out_spaced_doppler_13_0 => out_spaced_doppler_13_0_load_reg_2895,
        out_spaced_doppler_14_0 => out_spaced_doppler_14_0_load_reg_2900,
        out_spaced_doppler_15_0 => out_spaced_doppler_15_0_load_reg_2905,
        sext_ln5003 => top_in_doppler_load_reg_2809,
        count => count_load_1_reg_2990,
        far_enough_out => grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_far_enough_out,
        far_enough_out_ap_vld => grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_far_enough_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_ready = ap_const_logic_1)) then 
                    grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln4986_fu_1309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_ready = ap_const_logic_1)) then 
                    grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_ready = ap_const_logic_1)) then 
                    grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_fu_452_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                count_fu_452 <= ap_const_lv32_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                count_fu_452 <= count_1_fu_2187_p2;
            end if; 
        end if;
    end process;

    out_spaced_doppler_0_0_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_0_0_fu_196 <= p_read;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_0) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_0_0_fu_196 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_10_0_fu_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_10_0_fu_304 <= p_read10;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_A) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_10_0_fu_304 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_11_0_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_11_0_fu_316 <= p_read11;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_B) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_11_0_fu_316 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_1214_0_fu_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_1214_0_fu_328 <= p_read12;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_C) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_1214_0_fu_328 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_13_0_fu_340_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_13_0_fu_340 <= p_read13;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_D) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_13_0_fu_340 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_14_0_fu_352_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_14_0_fu_352 <= p_read14;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_E) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_14_0_fu_352 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_15_0_fu_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_15_0_fu_364 <= p_read15;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_F) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_15_0_fu_364 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_1_0_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_1_0_fu_200 <= p_read1;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_1) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_1_0_fu_200 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_2_0_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_2_0_fu_208 <= p_read2;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_2) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_2_0_fu_208 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_3_0_fu_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_3_0_fu_220 <= p_read3;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_3) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_3_0_fu_220 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_4_0_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_4_0_fu_232 <= p_read4;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_4) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_4_0_fu_232 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_5_0_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_5_0_fu_244 <= p_read5;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_5) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_5_0_fu_244 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_6_0_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_6_0_fu_256 <= p_read6;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_6) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_6_0_fu_256 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_7_0_fu_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_7_0_fu_268 <= p_read7;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_7) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_7_0_fu_268 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_8_0_fu_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_8_0_fu_280 <= p_read8;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_8) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_8_0_fu_280 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_doppler_9_0_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_doppler_9_0_fu_292 <= p_read9;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_9) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_doppler_9_0_fu_292 <= top_in_doppler_load_reg_2809;
            end if; 
        end if;
    end process;

    out_spaced_phase_0_0_fu_376_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_0_0_fu_376 <= p_read16;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_0) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_0_0_fu_376 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_10_0_fu_416_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_10_0_fu_416 <= p_read26;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_A) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_10_0_fu_416 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_11_0_fu_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_11_0_fu_412 <= p_read27;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_B) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_11_0_fu_412 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_12_0_fu_408_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_12_0_fu_408 <= p_read28;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_C) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_12_0_fu_408 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_13_0_fu_404_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_13_0_fu_404 <= p_read29;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_D) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_13_0_fu_404 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_14_0_fu_400_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_14_0_fu_400 <= p_read30;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_E) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_14_0_fu_400 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_15_0_fu_396_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_15_0_fu_396 <= p_read31;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_F) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_15_0_fu_396 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_1_0_fu_388_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_1_0_fu_388 <= p_read17;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_1) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_1_0_fu_388 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_2_0_fu_448_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_2_0_fu_448 <= p_read18;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_2) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_2_0_fu_448 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_3_0_fu_444_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_3_0_fu_444 <= p_read19;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_3) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_3_0_fu_444 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_4_0_fu_440_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_4_0_fu_440 <= p_read20;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_4) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_4_0_fu_440 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_5_0_fu_436_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_5_0_fu_436 <= p_read21;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_5) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_5_0_fu_436 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_6_0_fu_432_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_6_0_fu_432 <= p_read22;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_6) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_6_0_fu_432 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_7_0_fu_428_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_7_0_fu_428 <= p_read23;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_7) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_7_0_fu_428 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_8_0_fu_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_8_0_fu_424 <= p_read24;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_8) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_8_0_fu_424 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    out_spaced_phase_9_0_fu_420_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_spaced_phase_9_0_fu_420 <= p_read25;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_9) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                out_spaced_phase_9_0_fu_420 <= top_in_phase_load_reg_2788;
            end if; 
        end if;
    end process;

    r_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                r_fu_192 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                r_fu_192 <= r_2_reg_2764;
            end if; 
        end if;
    end process;

    write_flag37_0_fu_380_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag37_0_fu_380 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_1) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag37_0_fu_380 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag40_0_fu_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag40_0_fu_368 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_2) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag40_0_fu_368 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag43_0_fu_356_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag43_0_fu_356 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_3) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag43_0_fu_356 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag46_0_fu_344_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag46_0_fu_344 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_4) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag46_0_fu_344 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag49_0_fu_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag49_0_fu_332 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_5) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag49_0_fu_332 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag52_0_fu_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag52_0_fu_320 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_6) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag52_0_fu_320 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag55_0_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag55_0_fu_308 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_7) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag55_0_fu_308 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag58_0_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag58_0_fu_296 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_8) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag58_0_fu_296 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag61_0_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag61_0_fu_284 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_9) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag61_0_fu_284 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag64_0_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag64_0_fu_272 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_A) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag64_0_fu_272 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag67_0_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag67_0_fu_260 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_B) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag67_0_fu_260 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag70_0_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag70_0_fu_248 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_C) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag70_0_fu_248 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag73_0_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag73_0_fu_236 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_D) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag73_0_fu_236 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag76_0_fu_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag76_0_fu_224 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_E) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag76_0_fu_224 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag79_0_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag79_0_fu_212 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_F) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag79_0_fu_212 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    write_flag_0_fu_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                write_flag_0_fu_392 <= ap_const_lv1_0;
            elsif (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_0) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                write_flag_0_fu_392 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                and_ln5016_reg_3001 <= and_ln5016_fu_1882_p2;
                trunc_ln5017_1_reg_3010 <= trunc_ln5017_1_fu_1896_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                count_load_1_reg_2990 <= count_fu_452;
                icmp_ln5016_reg_2996 <= icmp_ln5016_fu_1873_p2;
                out_spaced_doppler_0_0_load_reg_2830 <= out_spaced_doppler_0_0_fu_196;
                out_spaced_doppler_10_0_load_reg_2880 <= out_spaced_doppler_10_0_fu_304;
                out_spaced_doppler_11_0_load_reg_2885 <= out_spaced_doppler_11_0_fu_316;
                out_spaced_doppler_1214_0_load_reg_2890 <= out_spaced_doppler_1214_0_fu_328;
                out_spaced_doppler_13_0_load_reg_2895 <= out_spaced_doppler_13_0_fu_340;
                out_spaced_doppler_14_0_load_reg_2900 <= out_spaced_doppler_14_0_fu_352;
                out_spaced_doppler_15_0_load_reg_2905 <= out_spaced_doppler_15_0_fu_364;
                out_spaced_doppler_1_0_load_reg_2835 <= out_spaced_doppler_1_0_fu_200;
                out_spaced_doppler_2_0_load_reg_2840 <= out_spaced_doppler_2_0_fu_208;
                out_spaced_doppler_3_0_load_reg_2845 <= out_spaced_doppler_3_0_fu_220;
                out_spaced_doppler_4_0_load_reg_2850 <= out_spaced_doppler_4_0_fu_232;
                out_spaced_doppler_5_0_load_reg_2855 <= out_spaced_doppler_5_0_fu_244;
                out_spaced_doppler_6_0_load_reg_2860 <= out_spaced_doppler_6_0_fu_256;
                out_spaced_doppler_7_0_load_reg_2865 <= out_spaced_doppler_7_0_fu_268;
                out_spaced_doppler_8_0_load_reg_2870 <= out_spaced_doppler_8_0_fu_280;
                out_spaced_doppler_9_0_load_reg_2875 <= out_spaced_doppler_9_0_fu_292;
                out_spaced_phase_0_0_load_reg_2910 <= out_spaced_phase_0_0_fu_376;
                out_spaced_phase_10_0_load_reg_2945 <= out_spaced_phase_10_0_fu_416;
                out_spaced_phase_11_0_load_reg_2940 <= out_spaced_phase_11_0_fu_412;
                out_spaced_phase_12_0_load_reg_2935 <= out_spaced_phase_12_0_fu_408;
                out_spaced_phase_13_0_load_reg_2930 <= out_spaced_phase_13_0_fu_404;
                out_spaced_phase_14_0_load_reg_2925 <= out_spaced_phase_14_0_fu_400;
                out_spaced_phase_15_0_load_reg_2920 <= out_spaced_phase_15_0_fu_396;
                out_spaced_phase_1_0_load_reg_2915 <= out_spaced_phase_1_0_fu_388;
                out_spaced_phase_2_0_load_reg_2985 <= out_spaced_phase_2_0_fu_448;
                out_spaced_phase_3_0_load_reg_2980 <= out_spaced_phase_3_0_fu_444;
                out_spaced_phase_4_0_load_reg_2975 <= out_spaced_phase_4_0_fu_440;
                out_spaced_phase_5_0_load_reg_2970 <= out_spaced_phase_5_0_fu_436;
                out_spaced_phase_6_0_load_reg_2965 <= out_spaced_phase_6_0_fu_432;
                out_spaced_phase_7_0_load_reg_2960 <= out_spaced_phase_7_0_fu_428;
                out_spaced_phase_8_0_load_reg_2955 <= out_spaced_phase_8_0_fu_424;
                out_spaced_phase_9_0_load_reg_2950 <= out_spaced_phase_9_0_fu_420;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                empty_126_reg_2773 <= empty_126_fu_1839_p1;
                tmp_11_reg_2769 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out(31 downto 31);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_0) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_0_064_fu_384 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_A) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_10_054_fu_264 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_B) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_11_053_fu_252 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_C) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_12_052_fu_240 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_D) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_13_051_fu_228 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_E) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_14_050_fu_216 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_F) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_15_049_fu_204 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_1) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_1_063_fu_372 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_2) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_2_062_fu_360 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_3) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_3_061_fu_348 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_4) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_4_060_fu_336 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_5) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_5_059_fu_324 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_6) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_6_058_fu_312 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_7) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_7_057_fu_300 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_8) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_8_056_fu_288 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln5016_reg_3001) and (trunc_ln5017_1_reg_3010 = ap_const_lv4_9) and (tmp_11_reg_2769 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                out_spaced_power_9_055_fu_276 <= top_in_power_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                r_2_reg_2764 <= r_2_fu_1315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    tmp_10_reg_2755(5 downto 4) <= tmp_10_fu_1298_p3(5 downto 4);
                    tmp_9_reg_2750(5 downto 4) <= tmp_9_fu_1286_p3(5 downto 4);
                    tmp_reg_2745(5 downto 4) <= tmp_fu_1274_p3(5 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                top_in_doppler_load_reg_2809 <= top_in_doppler_q0;
                top_in_phase_load_reg_2788 <= top_in_phase_q0;
            end if;
        end if;
    end process;
    tmp_reg_2745(3 downto 0) <= "0000";
    tmp_9_reg_2750(3 downto 0) <= "0000";
    tmp_10_reg_2755(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, tmp_11_fu_1826_p3, ap_CS_fsm_state5, grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_done, grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_done, grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_done, icmp_ln4986_fu_1309_p2, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln4986_fu_1309_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((tmp_11_fu_1826_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    add_ln5017_fu_1887_p2 <= std_logic_vector(unsigned(tmp_10_reg_2755) + unsigned(empty_126_reg_2773));
    and_ln5016_fu_1882_p2 <= (icmp_ln5016_reg_2996 and grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_far_enough_out);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_done)
    begin
        if ((grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_done)
    begin
        if ((grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_done)
    begin
        if ((grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln4986_fu_1309_p2)
    begin
        if ((((icmp_ln4986_fu_1309_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln4986_fu_1309_p2)
    begin
        if (((icmp_ln4986_fu_1309_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= out_spaced_doppler_0_0_fu_196;
    ap_return_1 <= out_spaced_doppler_1_0_fu_200;
    ap_return_10 <= out_spaced_doppler_10_0_fu_304;
    ap_return_11 <= out_spaced_doppler_11_0_fu_316;
    ap_return_12 <= out_spaced_doppler_1214_0_fu_328;
    ap_return_13 <= out_spaced_doppler_13_0_fu_340;
    ap_return_14 <= out_spaced_doppler_14_0_fu_352;
    ap_return_15 <= out_spaced_doppler_15_0_fu_364;
    ap_return_16 <= out_spaced_phase_0_0_fu_376;
    ap_return_17 <= out_spaced_phase_1_0_fu_388;
    ap_return_18 <= out_spaced_phase_2_0_fu_448;
    ap_return_19 <= out_spaced_phase_3_0_fu_444;
    ap_return_2 <= out_spaced_doppler_2_0_fu_208;
    ap_return_20 <= out_spaced_phase_4_0_fu_440;
    ap_return_21 <= out_spaced_phase_5_0_fu_436;
    ap_return_22 <= out_spaced_phase_6_0_fu_432;
    ap_return_23 <= out_spaced_phase_7_0_fu_428;
    ap_return_24 <= out_spaced_phase_8_0_fu_424;
    ap_return_25 <= out_spaced_phase_9_0_fu_420;
    ap_return_26 <= out_spaced_phase_10_0_fu_416;
    ap_return_27 <= out_spaced_phase_11_0_fu_412;
    ap_return_28 <= out_spaced_phase_12_0_fu_408;
    ap_return_29 <= out_spaced_phase_13_0_fu_404;
    ap_return_3 <= out_spaced_doppler_3_0_fu_220;
    ap_return_30 <= out_spaced_phase_14_0_fu_400;
    ap_return_31 <= out_spaced_phase_15_0_fu_396;
    ap_return_32 <= select_ln5024_fu_1417_p3;
    ap_return_33 <= select_ln5024_1_fu_1424_p3;
    ap_return_34 <= select_ln5024_2_fu_1431_p3;
    ap_return_35 <= select_ln5024_3_fu_1438_p3;
    ap_return_36 <= select_ln5024_4_fu_1445_p3;
    ap_return_37 <= select_ln5024_5_fu_1452_p3;
    ap_return_38 <= select_ln5024_6_fu_1459_p3;
    ap_return_39 <= select_ln5024_7_fu_1466_p3;
    ap_return_4 <= out_spaced_doppler_4_0_fu_232;
    ap_return_40 <= select_ln5024_8_fu_1473_p3;
    ap_return_41 <= select_ln5024_9_fu_1480_p3;
    ap_return_42 <= select_ln5024_10_fu_1487_p3;
    ap_return_43 <= select_ln5024_11_fu_1494_p3;
    ap_return_44 <= select_ln5024_12_fu_1501_p3;
    ap_return_45 <= select_ln5024_13_fu_1508_p3;
    ap_return_46 <= select_ln5024_14_fu_1515_p3;
    ap_return_47 <= select_ln5024_15_fu_1522_p3;
    ap_return_48 <= count_fu_452;
    ap_return_5 <= out_spaced_doppler_5_0_fu_244;
    ap_return_6 <= out_spaced_doppler_6_0_fu_256;
    ap_return_7 <= out_spaced_doppler_7_0_fu_268;
    ap_return_8 <= out_spaced_doppler_8_0_fu_280;
    ap_return_9 <= out_spaced_doppler_9_0_fu_292;
    count_1_fu_2187_p2 <= std_logic_vector(unsigned(count_fu_452) + unsigned(ap_const_lv32_1));
    empty_125_fu_1282_p1 <= top_in_doppler_offset(2 - 1 downto 0);
    empty_126_fu_1839_p1 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out(6 - 1 downto 0);
    empty_127_fu_1843_p2 <= std_logic_vector(unsigned(tmp_reg_2745) + unsigned(empty_126_fu_1839_p1));
    empty_128_fu_1853_p2 <= std_logic_vector(unsigned(tmp_9_reg_2750) + unsigned(empty_126_fu_1839_p1));
    empty_fu_1270_p1 <= top_in_phase_offset(2 - 1 downto 0);
    grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start <= grp_select_spaced_topk_1_Pipeline_CHECK_SEP_LOOP_fu_848_ap_start_reg;
    grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_ap_start_reg;
    grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start <= grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_ap_start_reg;
    icmp_ln4986_fu_1309_p2 <= "1" when (r_fu_192 = ap_const_lv5_10) else "0";
    icmp_ln5016_fu_1873_p2 <= "1" when (signed(tmp_12_fu_1863_p4) < signed(ap_const_lv30_1)) else "0";
    idxprom32_fu_1834_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out),64));
    p_cast53_fu_1858_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_128_fu_1853_p2),64));
    p_cast_fu_1848_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_127_fu_1843_p2),64));
    r_2_fu_1315_p2 <= std_logic_vector(unsigned(r_fu_192) + unsigned(ap_const_lv5_1));
    select_ln5024_10_fu_1487_p3 <= 
        out_spaced_power_10_054_fu_264 when (write_flag64_0_fu_272(0) = '1') else 
        p_read42;
    select_ln5024_11_fu_1494_p3 <= 
        out_spaced_power_11_053_fu_252 when (write_flag67_0_fu_260(0) = '1') else 
        p_read43;
    select_ln5024_12_fu_1501_p3 <= 
        out_spaced_power_12_052_fu_240 when (write_flag70_0_fu_248(0) = '1') else 
        p_read44;
    select_ln5024_13_fu_1508_p3 <= 
        out_spaced_power_13_051_fu_228 when (write_flag73_0_fu_236(0) = '1') else 
        p_read45;
    select_ln5024_14_fu_1515_p3 <= 
        out_spaced_power_14_050_fu_216 when (write_flag76_0_fu_224(0) = '1') else 
        p_read46;
    select_ln5024_15_fu_1522_p3 <= 
        out_spaced_power_15_049_fu_204 when (write_flag79_0_fu_212(0) = '1') else 
        p_read47;
    select_ln5024_1_fu_1424_p3 <= 
        out_spaced_power_1_063_fu_372 when (write_flag37_0_fu_380(0) = '1') else 
        p_read33;
    select_ln5024_2_fu_1431_p3 <= 
        out_spaced_power_2_062_fu_360 when (write_flag40_0_fu_368(0) = '1') else 
        p_read34;
    select_ln5024_3_fu_1438_p3 <= 
        out_spaced_power_3_061_fu_348 when (write_flag43_0_fu_356(0) = '1') else 
        p_read35;
    select_ln5024_4_fu_1445_p3 <= 
        out_spaced_power_4_060_fu_336 when (write_flag46_0_fu_344(0) = '1') else 
        p_read36;
    select_ln5024_5_fu_1452_p3 <= 
        out_spaced_power_5_059_fu_324 when (write_flag49_0_fu_332(0) = '1') else 
        p_read37;
    select_ln5024_6_fu_1459_p3 <= 
        out_spaced_power_6_058_fu_312 when (write_flag52_0_fu_320(0) = '1') else 
        p_read38;
    select_ln5024_7_fu_1466_p3 <= 
        out_spaced_power_7_057_fu_300 when (write_flag55_0_fu_308(0) = '1') else 
        p_read39;
    select_ln5024_8_fu_1473_p3 <= 
        out_spaced_power_8_056_fu_288 when (write_flag58_0_fu_296(0) = '1') else 
        p_read40;
    select_ln5024_9_fu_1480_p3 <= 
        out_spaced_power_9_055_fu_276 when (write_flag61_0_fu_284(0) = '1') else 
        p_read41;
    select_ln5024_fu_1417_p3 <= 
        out_spaced_power_0_064_fu_384 when (write_flag_0_fu_392(0) = '1') else 
        p_read32;
    tmp_10_fu_1298_p3 <= (trunc_ln5017_fu_1294_p1 & ap_const_lv4_0);
    tmp_11_fu_1826_p3 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_best_idx_out(31 downto 31);
    tmp_12_fu_1863_p4 <= count_fu_452(31 downto 2);
    tmp_9_fu_1286_p3 <= (empty_125_fu_1282_p1 & ap_const_lv4_0);
    tmp_fu_1274_p3 <= (empty_fu_1270_p1 & ap_const_lv4_0);
    top_in_doppler_address0 <= p_cast53_fu_1858_p1(6 - 1 downto 0);

    top_in_doppler_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            top_in_doppler_ce0 <= ap_const_logic_1;
        else 
            top_in_doppler_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    top_in_phase_address0 <= p_cast_fu_1848_p1(6 - 1 downto 0);

    top_in_phase_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            top_in_phase_ce0 <= ap_const_logic_1;
        else 
            top_in_phase_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    top_in_power_address0_assign_proc : process(ap_CS_fsm_state9, grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_address0, ap_CS_fsm_state4, zext_ln5017_fu_1891_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            top_in_power_address0 <= zext_ln5017_fu_1891_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            top_in_power_address0 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_address0;
        else 
            top_in_power_address0 <= "XXXXXX";
        end if; 
    end process;


    top_in_power_ce0_assign_proc : process(ap_CS_fsm_state9, grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_ce0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            top_in_power_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            top_in_power_ce0 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_top_in_power_ce0;
        else 
            top_in_power_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln5017_1_fu_1896_p1 <= count_load_1_reg_2990(4 - 1 downto 0);
    trunc_ln5017_fu_1294_p1 <= top_in_power_offset(2 - 1 downto 0);

    used_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_address0, grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_address0, ap_CS_fsm_state4, idxprom32_fu_1834_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            used_address0 <= idxprom32_fu_1834_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            used_address0 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            used_address0 <= grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_address0;
        else 
            used_address0 <= "XXXX";
        end if; 
    end process;


    used_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_ce0, grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_ce0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            used_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            used_ce0 <= grp_select_spaced_topk_1_Pipeline_FIND_BEST_UNUSED_fu_838_used_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            used_ce0 <= grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_ce0;
        else 
            used_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    used_d0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_d0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            used_d0 <= ap_const_lv1_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            used_d0 <= grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_d0;
        else 
            used_d0 <= "X";
        end if; 
    end process;


    used_we0_assign_proc : process(ap_CS_fsm_state2, tmp_11_fu_1826_p3, ap_CS_fsm_state5, grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_we0)
    begin
        if (((tmp_11_fu_1826_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            used_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            used_we0 <= grp_select_spaced_topk_1_Pipeline_INIT_USED_fu_832_used_we0;
        else 
            used_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln5017_fu_1891_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln5017_fu_1887_p2),64));
end behav;
