-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity acquisition_stsa_top_coarse_search_Pipeline_SQ_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    diff_buf : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_1 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_2 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_3 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_4 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_5 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_6 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_7 : IN STD_LOGIC_VECTOR (23 downto 0);
    diff_buf_8 : IN STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_8_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_8_out_ap_vld : OUT STD_LOGIC;
    sq_buf_7_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_7_out_ap_vld : OUT STD_LOGIC;
    sq_buf_6_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_6_out_ap_vld : OUT STD_LOGIC;
    sq_buf_5_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_5_out_ap_vld : OUT STD_LOGIC;
    sq_buf_4_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_4_out_ap_vld : OUT STD_LOGIC;
    sq_buf_3_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_3_out_ap_vld : OUT STD_LOGIC;
    sq_buf_2_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_2_out_ap_vld : OUT STD_LOGIC;
    sq_buf_1_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_1_out_ap_vld : OUT STD_LOGIC;
    sq_buf_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    sq_buf_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of acquisition_stsa_top_coarse_search_Pipeline_SQ_LOOP is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1667_fu_267_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_reg_486 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_486_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_486_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln1667_reg_490 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1667_reg_490_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln1670_fu_323_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal i_5_fu_98 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln1667_fu_273_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sq_buf_fu_102 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_1_fu_106 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_2_fu_110 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_3_fu_114 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_4_fu_118 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_5_fu_122 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_6_fu_126 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_7_fu_130 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal sq_buf_8_fu_134 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_255_p0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_255_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal d_fu_279_p19 : STD_LOGIC_VECTOR (23 downto 0);
    signal d_fu_279_p21 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_255_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal d_fu_279_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal d_fu_279_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component acquisition_stsa_top_mul_24s_24s_48_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component acquisition_stsa_top_sparsemux_19_4_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        din4 : IN STD_LOGIC_VECTOR (23 downto 0);
        din5 : IN STD_LOGIC_VECTOR (23 downto 0);
        din6 : IN STD_LOGIC_VECTOR (23 downto 0);
        din7 : IN STD_LOGIC_VECTOR (23 downto 0);
        din8 : IN STD_LOGIC_VECTOR (23 downto 0);
        def : IN STD_LOGIC_VECTOR (23 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component acquisition_stsa_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_24s_24s_48_4_1_U635 : component acquisition_stsa_top_mul_24s_24s_48_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_255_p0,
        din1 => grp_fu_255_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_255_p2);

    sparsemux_19_4_24_1_1_U636 : component acquisition_stsa_top_sparsemux_19_4_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 24,
        CASE1 => "0001",
        din1_WIDTH => 24,
        CASE2 => "0010",
        din2_WIDTH => 24,
        CASE3 => "0011",
        din3_WIDTH => 24,
        CASE4 => "0100",
        din4_WIDTH => 24,
        CASE5 => "0101",
        din5_WIDTH => 24,
        CASE6 => "0110",
        din6_WIDTH => 24,
        CASE7 => "0111",
        din7_WIDTH => 24,
        CASE8 => "1000",
        din8_WIDTH => 24,
        def_WIDTH => 24,
        sel_WIDTH => 4,
        dout_WIDTH => 24)
    port map (
        din0 => diff_buf,
        din1 => diff_buf_1,
        din2 => diff_buf_2,
        din3 => diff_buf_3,
        din4 => diff_buf_4,
        din5 => diff_buf_5,
        din6 => diff_buf_6,
        din7 => diff_buf_7,
        din8 => diff_buf_8,
        def => d_fu_279_p19,
        sel => ap_sig_allocacmp_i,
        dout => d_fu_279_p21);

    flow_control_loop_pipe_sequential_init_U : component acquisition_stsa_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    i_5_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1667_fu_267_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_5_fu_98 <= add_ln1667_fu_273_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_5_fu_98 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_reg_486 <= ap_sig_allocacmp_i;
                i_reg_486_pp0_iter1_reg <= i_reg_486;
                icmp_ln1667_reg_490 <= icmp_ln1667_fu_267_p2;
                icmp_ln1667_reg_490_pp0_iter1_reg <= icmp_ln1667_reg_490;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                i_reg_486_pp0_iter2_reg <= i_reg_486_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_7))) then
                sq_buf_1_fu_106 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_6))) then
                sq_buf_2_fu_110 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_5))) then
                sq_buf_3_fu_114 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_4))) then
                sq_buf_4_fu_118 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_3))) then
                sq_buf_5_fu_122 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_2))) then
                sq_buf_6_fu_126 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_1))) then
                sq_buf_7_fu_130 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (i_reg_486_pp0_iter2_reg = ap_const_lv4_0))) then
                sq_buf_8_fu_134 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((i_reg_486_pp0_iter2_reg = ap_const_lv4_7)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_6)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_5)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_4)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_3)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_2)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_1)) and not((i_reg_486_pp0_iter2_reg = ap_const_lv4_0)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                sq_buf_fu_102 <= grp_fu_255_p2(43 downto 20);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1667_fu_273_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1667_fu_267_p2)
    begin
        if (((icmp_ln1667_fu_267_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, i_5_fu_98, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i <= i_5_fu_98;
        end if; 
    end process;

    d_fu_279_p19 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
    grp_fu_255_p0 <= sext_ln1670_fu_323_p1(24 - 1 downto 0);
    grp_fu_255_p1 <= sext_ln1670_fu_323_p1(24 - 1 downto 0);
    icmp_ln1667_fu_267_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv4_9) else "0";
        sext_ln1670_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_fu_279_p21),48));

    sq_buf_1_out <= sq_buf_1_fu_106;

    sq_buf_1_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_1_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_2_out <= sq_buf_2_fu_110;

    sq_buf_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_2_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_3_out <= sq_buf_3_fu_114;

    sq_buf_3_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_3_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_4_out <= sq_buf_4_fu_118;

    sq_buf_4_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_4_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_5_out <= sq_buf_5_fu_122;

    sq_buf_5_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_5_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_6_out <= sq_buf_6_fu_126;

    sq_buf_6_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_6_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_7_out <= sq_buf_7_fu_130;

    sq_buf_7_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_7_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_8_out <= sq_buf_8_fu_134;

    sq_buf_8_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_8_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    sq_buf_out <= sq_buf_fu_102;

    sq_buf_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln1667_reg_490_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1667_reg_490_pp0_iter1_reg = ap_const_lv1_1))) then 
            sq_buf_out_ap_vld <= ap_const_logic_1;
        else 
            sq_buf_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
