// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module acquisition_serial_m_axi_store_stream_to_mem (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        sig_s_dout,
        sig_s_num_data_valid,
        sig_s_fifo_cap,
        sig_s_empty_n,
        sig_s_read,
        prn_s_dout,
        prn_s_num_data_valid,
        prn_s_fifo_cap,
        prn_s_empty_n,
        prn_s_read,
        signal_buf_address0,
        signal_buf_ce0,
        signal_buf_we0,
        signal_buf_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1:0] sig_s_dout;
input  [6:0] sig_s_num_data_valid;
input  [6:0] sig_s_fifo_cap;
input   sig_s_empty_n;
output   sig_s_read;
input  [0:0] prn_s_dout;
input  [6:0] prn_s_num_data_valid;
input  [6:0] prn_s_fifo_cap;
input   prn_s_empty_n;
output   prn_s_read;
output  [13:0] signal_buf_address0;
output   signal_buf_ce0;
output   signal_buf_we0;
output  [1:0] signal_buf_d0;
output  [13:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_d0;
output  [13:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_d0;

reg ap_idle;
reg sig_s_read;
reg prn_s_read;
reg signal_buf_ce0;
reg signal_buf_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln434_fu_114_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    sig_s_blk_n;
wire    ap_block_pp0_stage0;
reg    prn_s_blk_n;
reg   [13:0] i_1_reg_160;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln434_fu_131_p1;
wire   [63:0] zext_ln434_1_fu_147_p1;
reg   [13:0] i_fu_48;
wire   [13:0] add_ln434_fu_120_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_i_1;
wire   [0:0] trunc_ln434_fu_135_p1;
wire   [12:0] lshr_ln_fu_138_p4;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_118;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_48 = 14'd0;
end

acquisition_serial_m_axi_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_118)) begin
        if ((icmp_ln434_fu_114_p2 == 1'd0)) begin
            i_fu_48 <= add_ln434_fu_120_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_160 <= ap_sig_allocacmp_i_1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln434_fu_135_p1 == 1'd1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln434_fu_135_p1 == 1'd0))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln434_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 14'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prn_s_blk_n = prn_s_empty_n;
    end else begin
        prn_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prn_s_read = 1'b1;
    end else begin
        prn_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sig_s_blk_n = sig_s_empty_n;
    end else begin
        sig_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sig_s_read = 1'b1;
    end else begin
        sig_s_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        signal_buf_ce0 = 1'b1;
    end else begin
        signal_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        signal_buf_we0 = 1'b1;
    end else begin
        signal_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_address0 = zext_ln434_1_fu_147_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_d0 = prn_s_dout;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_address0 = zext_ln434_1_fu_147_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_d0 = prn_s_dout;

assign add_ln434_fu_120_p2 = (ap_sig_allocacmp_i_1 + 14'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((prn_s_empty_n == 1'b0) | (sig_s_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_118 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln434_fu_114_p2 = ((ap_sig_allocacmp_i_1 == 14'd11999) ? 1'b1 : 1'b0);

assign lshr_ln_fu_138_p4 = {{i_1_reg_160[13:1]}};

assign signal_buf_address0 = zext_ln434_fu_131_p1;

assign signal_buf_d0 = sig_s_dout;

assign trunc_ln434_fu_135_p1 = i_1_reg_160[0:0];

assign zext_ln434_1_fu_147_p1 = lshr_ln_fu_138_p4;

assign zext_ln434_fu_131_p1 = i_1_reg_160;

endmodule //acquisition_serial_m_axi_store_stream_to_mem
