// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module acquisition_serial_m_axi_build_prn_banks (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_q0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_d0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_we0,
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0;
input  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_q0;
output  [13:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0;
input  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_q0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_d0;
output  [14:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0;
output   acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_we0;
output  [0:0] acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_d0;

reg ap_idle;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_we0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0;
reg acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln523_fu_190_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [14:0] i_19_reg_252;
wire    ap_block_pp0_stage0_11001;
reg   [14:0] i_19_reg_252_pp0_iter1_reg;
wire   [0:0] tmp_fu_226_p3;
reg   [0:0] tmp_reg_272;
wire   [63:0] zext_ln523_1_fu_212_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln523_fu_234_p1;
reg   [14:0] i_fu_48;
wire   [14:0] add_ln523_fu_196_p2;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_i_19;
wire   [13:0] lshr_ln_fu_202_p4;
wire   [0:0] trunc_ln523_fu_223_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_48 = 15'd0;
#0 ap_done_reg = 1'b0;
end

acquisition_serial_m_axi_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln523_fu_190_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_48 <= add_ln523_fu_196_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_48 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_19_reg_252 <= ap_sig_allocacmp_i_19;
        i_19_reg_252_pp0_iter1_reg <= i_19_reg_252;
        tmp_reg_272 <= tmp_fu_226_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_we0 = 1'b1;
    end else begin
        acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln523_fu_190_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_19 = 15'd0;
    end else begin
        ap_sig_allocacmp_i_19 = i_fu_48;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_10_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_11_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_12_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_13_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_address0 = zext_ln523_1_fu_212_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_address0 = zext_ln523_1_fu_212_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_6_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_7_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_8_d0 = tmp_reg_272;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_address0 = zext_ln523_fu_234_p1;

assign acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_9_d0 = tmp_reg_272;

assign add_ln523_fu_196_p2 = (ap_sig_allocacmp_i_19 + 15'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln523_fu_190_p2 = ((ap_sig_allocacmp_i_19 == 15'd23998) ? 1'b1 : 1'b0);

assign lshr_ln_fu_202_p4 = {{ap_sig_allocacmp_i_19[14:1]}};

assign tmp_fu_226_p3 = ((trunc_ln523_fu_223_p1[0:0] == 1'b1) ? acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_4_q0 : acquisition_serial_m_axi_ap_int_const_ap_int_const_ap_int_int_int_int_int_5_q0);

assign trunc_ln523_fu_223_p1 = i_19_reg_252[0:0];

assign zext_ln523_1_fu_212_p1 = lshr_ln_fu_202_p4;

assign zext_ln523_fu_234_p1 = i_19_reg_252_pp0_iter1_reg;

endmodule //acquisition_serial_m_axi_build_prn_banks
